In [1]:
# Load necessary modules
import warnings
warnings.filterwarnings('ignore')

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt
import matplotlib.backends.backend_pdf
from Bio import SeqIO
import glob, pickle, os, re, subprocess, csv, sys, io
from contextlib import redirect_stdout

from uuid import uuid4
import argparse
from tqdm import tqdm 
import time

sys.path.append(os.path.abspath('/global/scratch/projects/fc_mvslab/predictors'))
from adpred import ADpred as adp
# from PADDLE import paddle
from iupred3.iupred import get_iupred

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, Flatten, Dense, Dropout, Activation
from tensorflow.keras import regularizers
from tensorflow.keras.activations import softplus
from tensorflow.keras import backend as K
from tensorflow.keras import metrics

# Limit tensorflow thread usage
import os
import ipyparallel as ipp

# os.environ["OMP_NUM_THREADS"] = "1"
# os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
# os.environ["TF_NUM_INTEROP_THREADS"] = "1"

If you wish to use a local installation of psipred, please indicate this,
    by assigning the path to local_psipred (e.g. local_psipred = "~/psipred/run_psipred")

In [6]:
# Goal: Troubleshoot adpred for file 87

In [42]:
fasta_name = "../data/interpro_uniprot_evid_1_2_split/pt_77.fasta"
output_dir = "../output/interpro_uniprot_evid_1_2_dask/"

In [43]:
print("Loading sequences")
aa_lst = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']

fasta_name_tmp = fasta_name.split('/')[-1].removesuffix('.fasta').removesuffix('.fa')
recs = list(SeqIO.parse(fasta_name, 'fasta'))
fasta_name = fasta_name_tmp

seqs_to_keep = []
for r in recs:
    seq_str = str(r.seq)

    # Filtering sequences with too few AAs and non-standard AAs
    if (len(seq_str) < 30):
        print("Removing", seq_str, "because it is too short")
        continue
    elif (len(set(seq_str) - set(aa_lst)) > 0):
        print("Removing",seq_str, "because it contains non-standard amino acids")
        continue # No need for 
    else:
        seqs_to_keep.append(r)

recs = seqs_to_keep

Loading sequences

In [44]:
str(recs[710].seq)

'MAPPVQSQRLPPPSQPSGKGEVGELKTQLRQLAGSRAAGAEDLKRELYKKVISYMTVGIDVSSLFSEMVMCSATSDIVLKKMCYLYVGNYAKVHPDLALLTINFLQKDCQDEDPMIRGLALRSLCSLRVKNLVEYLVGPLRTGLQDSNSYVRTVAAIGALKLYHISPSTCIDSDFPVALKALMMHDPDAKVVASCLSSLQEILTLEGNASEEASKERELLLSKPVIYFLLNRIREFSEWAQCLVLDLVSKYVPSENSEIFDIMNLLEDRLQHANSAVVLATINVFLHLTISMADVHQQVYERIKAPLLTLVGSGSSEQSYAVLSHLHLLVMRAPILFSSDYKHFYCRYSDPSYVKKLKLEMLTAVANESNTYEIVTELSEYAANVDVLIARESIRAVGKIALQQYDVNAIVDRLLQFLEMEKDYVTAETLVLVKDLLRKYPQWSQDCIAVVGNVSSKNVEEPKAKAALVWMLGEYSQDMLDAPYILESLIDSWDEEDSAEVRLHLLTAVAKCFFKRPPETQKALGAALAAGLADAHQDVHDRALFYYRLLQHDVSVAERVINPPKQAVSVFADTQSSEVKDRIFDEFNSLSVIYQEPSYMFIDKEHRGPFEFSEDIGALATGASPDNSVLPSQRVEASDNDLLLSASEKEENRGIAANGSLAYSAPDYNGSSTALVSHSPSPTANTSAASGAPSTASISQPSIEIDDLLGLGPVTTPTPIPALKLNSKIVLDPATFQRKWGQLPIALTQDCSLTAQGIASLTSPQVLLRHMQGHLIQCIASGGQPPNFKFFFFAQKSEAPSGAGFFLVECLVNTSSSKAHVKVKADEASLSQDFAALFQSALLKFGVS'

In [25]:
def return_adpred_ss(r, output_dir):
    sequence = r.seq
    sub_fasta_name = re.sub(r'\s+', '_', r.id)
    computed="{}/ss/{}/{}.ss2".format(output_dir, sub_fasta_name, sub_fasta_name)
    df = pd.read_table(computed, 
                       skiprows=[0], sep='\s+', names=['position', 'residue', 'ss', 'c', 'h', 'e'])
    return ''.join(df.ss.values).replace('C','-')

In [26]:
return_adpred_ss(recs[711], output_dir)

'-------------HHH-------------------------HHH----------------------------------------------------------------------------HHHHHHHHHH--------HHHHHHHHHHH-HHHHH----HHHHHHHH-HHHH-EEEE-----------EEEE-HHHHHHH-----EE-------------HHHH---------------------------------------------------HHHHHHHH---'

In [28]:
adpred_ss_all = []
seqs = []
ids = []

for r in recs:
    adpred_ss_all.append(return_adpred_ss(r, output_dir))
    seqs.append(r.seq)
    ids.append(r.id)
    
ss_results = pd.DataFrame({"id" : ids, "seq" : seqs, "ss" : adpred_ss_all})
ss_results

,id,seq,ss
0,tr|A0A8G0VU03|A0A8G0VU03_9ROSI,"(M, S, N, S, Q, P, Q, N, T, S, T, Q, P, H, D, ...",------------------------HHH---------------HHH-...
1,tr|A0A8I3B0M7|A0A8I3B0M7_PONAB,"(M, N, D, F, G, I, K, N, M, D, Q, V, A, P, V, ...",--------HHHHH--HH------------------HHH--------...
2,tr|A0A8I3WJI5|A0A8I3WJI5_CALJA,"(M, L, D, P, K, C, D, R, K, R, A, R, E, F, I, ...",-------HHHHHHHH-----HHHH----------HHHHHHHHHHHH...
3,tr|A0A8J8YT14|A0A8J8YT14_CALJA,"(M, A, I, T, L, Q, P, S, D, L, I, F, E, F, A, ...",---EE----EEEEEE------HHHH--------EEEE-------HH...
4,tr|A0A8K0ZUK2|A0A8K0ZUK2_CHICK,"(M, A, G, A, R, D, P, L, R, R, P, P, R, P, P, ...",----------------------------------------------...
...,...,...,...
995,tr|F7HBY1|F7HBY1_CALJA,"(M, G, P, V, M, P, P, S, K, K, P, E, S, S, G, ...",----------------EE----------------------------...
996,tr|F7HFL8|F7HFL8_MACMU,"(M, M, Q, E, S, G, T, E, T, K, S, N, G, S, A, ...",------------------------HH----------------HHH-...
997,tr|F7HH72|F7HH72_CALJA,"(M, G, P, V, M, P, P, S, K, K, P, E, S, S, G, ...",----------------------------------------------...
998,tr|F7HIN3|F7HIN3_MACMU,"(M, C, D, R, N, G, G, R, R, L, R, Q, W, L, I, ...",----------HHHHHHHHHH-----EEEE----EEEEEE-------...
999,tr|F7HMZ1|F7HMZ1_CALJA,"(M, A, Q, S, G, G, E, A, R, P, G, P, E, T, T, ...",---------------HHHEEEEEE---HHHHHHHHHHHHH-----H...

In [29]:
ss_results[ss_results["ss"].isna()]

Empty DataFrame
Columns: [id, seq, ss]
Index: []

In [30]:
ss_results["ss"].value_counts()

ss
---------------EEEEEE--EEEE------EEE--EEEEEEEEEE---------HHHEEEEEE-----------EEEEEE------------------EEEEEEE---HHHHHHHHHHHHHH---HHH---------------EE--HHHHHHHHHHHHHHH--HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH-------HHHHHHHHHHH--------------HHHHHHHHHHHHHHHHH-HHHH----EEHHHHHHHHHHH-------HHHHHHHHHHHHH----EEEEEE----EEEE----HHHHHHHHHHHHHH-----HHHHHHHH-HHHHHHHHHHHHHHHH-----------------------                                                                                                                                                                         2
----HHHHHHHHHHHHH---EEE---------HHH-------HHHHHHHHHHHH---EEEEEEHHHHHHHHHHHHHHHHHHHH---HHH--HHHH--------------------------------HHH------------------------EE---------------                                                                                                                                                                                                                                                                                                                                                                                          2
-HHHHHHHHHHHHHHHHHHHHHH--HHHHHHHHHHHHHHHHHHHHHH-----HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH--HHHHHHHHHHHHH----HHHHHHHHHHHHHHHHHHH---------HHHHHHHHHHHHHHHHHHH----HHHHHHHHHHHHHHHH------HHHHHHHHHHHHHH------HHHHHHHHHHHHHHHHHHH-HHHHHHHHHHHHHHHHH------HHHHHHHHHHHHHHH-HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH--------EEEEEE----------------HHHHHHHHHHHHHHHHH----EEEE----EEEEEEEEE---EEEEEEEHHHHHHHHHHH----EEHHHHHHHH---HHHHHHHHHHHH-----EEEE------------EEE--------EEEEEE-------HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH----HHHHHHHHHHHH-----HHHHHHHHHHHHH-------------EEE--                     2
-----HHHHHHHHHHHHH------HHHHH----------------HHHHH-------HHHHHHHHHHHHHH-----HHHHHHHHHHHHHHHHHHHH-------HHHHHHHHHHHHHHHHHHHHHHHHH------HHHHHHHHHHHHHHHHHHH----------HHHHHHHHHHHHHHHHHHH--HHH-HHHHHHHH---------HHHHHHHHHHHHHHHHHH---HHHHHHHHHHHHH--HHHHHHHHHHHHHHHHHHHHH-----HHHH----HHHHHHHHHHHHH--HHHHHHHHHH-HHHHHH--HHHHHHHHHHHHHHHHHHHHHHH-------HHHHHHHH---------HHHHHHHHHHHHH-----EEEE----EEEE-------------                                                                                                                                                      2
----HH------HHHHHHHHHHH------HHHHHHHHHHH----HHHHHHHHHHHHH----EEEE---EEEEEE-HH------HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH---HHHHHHHHHHHHHHHHHHHHHHHHHHHH-----HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH-----HHHHHHHH----------------                                                                                                                                                                                                                                                                                                                                          2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
--------------EEEEE--EEE-----HHHHHHHHH---EEEEEEEEEEEE----------EEEEEEEEEEEEE----HHHHHHHHHH-------EEEE--HHHHHHEEEEE--HHH-----HHHHHHHHHH------HHHH----------------HHHHH--------------------HHHHHHHHHHHHHHHHHHH----HHHHHHHHHHHHHHHHHHHHHH--HHHHHHH-----HHHHHHH----HHHHHHHHHHHHH---EE-----EE--HHHHHH--------HHHHHHHH-HHHHHHHHHHHHHHHH---HHHHH----HHHHHHHHHHH-HHHHHHHHHHHHHHHHHHHHHHHHH---HH--EEEEE----HHHHHHHHHH----EEEEEE-HHHHHHHHHH---------EEEEE------------EEEEE--HH---HHHHHHHHHHHHHH-----EEEEEEEE------HHHHHHHHHHHHHHH-------HHHHHHHHHH---EEEEEEE----EEEEEEEEE--    1
----------------------------------------HHHH-EEE--HHHHHH-------EEE--EEEEEEEEEEEEE-------EEEEEEEEEEEEEE----------------EEEEEEEEE-----EEEEEEEEEE----HHHHHHHHHHHHHHHHHH------------------------------------HHHHHHHHHHHH--------HHHHHHHH----HHHHHHHHHHHHH---EE----HHH-------                                                                                                                                                                                                                                                                                             1
-------------------------HH----HHHH------------------------------HHH-EEEE--HH----EEEEE------EEEE-------EEEEEEE--------EEE-EEEEE----HH-----------------------------EE----HHHHH--HHHHHHHHHHHHH--HHHHHHHHHHHHHHHHHHHHHH---HHHHHHHHHHH------------------------------------------------------------HHHH----HHHH-------HHHHHHHHHHHH-------HHHHHHHHHHH-HHHH---HHHHHHHHHH------EEEE------EEEE-HHHHHHHH--------------                                                                                                                                                         1
--------------HHHH-------------------------------HHHHHHHHHHH-------HHHHHHHHHHH-HHHH-----HHHHHHHH--HHH-EEE-------------EEE--HHH-------EE-------HHHHHHHHHHHHHHH--HHHHH---HHHHHH-----------------------------------------------------HHHHHHHH------------HHH--------------HHHH---------------------HHHH---------------------------------------------------                                                                                                                                                                                                              1
-------------------------------HHHH-----------------------------------------------HHHHHHHHHH--------HHHHHHHHHHH-HHHH---HHHHHHHHHH--HHH-EEEE-----------EEEE-HHHHHHH--------HHH------HHHHHHHHHHHH------------------------------------------------------------------------------------------------------------------------------------------------------HHH--                                                                                                                                                                                                           1
Name: count, Length: 994, dtype: int64

In [32]:
def make_pred(r):
    sequence = r.seq
    
    adp_prot = adp.protein('x', sequence)
    # Load pre-computed secondary structure predicted by PSIPRED V4.
    adp_prot.second_struct = return_adpred_ss(r, output_dir)
    # Run ADpred
    adp_prot.predict()
    adpred_preds = adp_prot.predictions
    return adpred_preds

In [33]:
%%time
results = make_pred(recs[711])
results

1/1 [==============================] - 6s 6s/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 35ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
CPU times: user 9.42 s, sys: 186 ms, total: 9.6 s
Wall time: 17.5 s

array([8.92296666e-04, 8.65946349e-04, 1.04481389e-03, 6.79613615e-04,
       6.73374045e-04, 6.61538914e-04, 4.12585068e-04, 4.66680329e-04,
       5.71319833e-04, 5.31609694e-04, 3.28547932e-04, 6.40054874e-04,
       4.17759555e-04, 7.16565584e-04, 7.43842160e-04, 1.22487533e-03,
       7.77626468e-04, 5.42941329e-04, 4.88006190e-04, 5.44368348e-04,
       1.12039060e-03, 1.52285653e-03, 1.32968149e-03, 1.00295758e-03,
       4.24980972e-04, 4.30522399e-04, 4.59961389e-04, 4.46418300e-04,
       6.76790369e-04, 6.89300126e-04, 3.16023856e-04, 2.25990501e-04,
       1.18492586e-04, 1.48584077e-04, 8.49862336e-05, 1.34160058e-04,
       2.58141023e-04, 2.86448776e-04, 2.49136792e-04, 2.26908756e-04,
       2.86289054e-04, 2.57982552e-04, 1.92943291e-04, 2.81025394e-04,
       3.51707247e-04, 3.31405929e-04, 3.51686118e-04, 3.04041430e-04,
       3.33066593e-04, 2.08364712e-04, 1.54508583e-04, 1.96754947e-04,
       1.58642113e-04, 1.33421418e-04, 1.04580969e-04, 6.99872035e-05,
       5.39844623e-05, 6.91279638e-05, 5.75825325e-05, 7.63127973e-05,
       7.82638017e-05, 8.53029633e-05, 8.58135463e-05, 8.85871486e-05,
       7.63777280e-05, 7.36537550e-05, 6.23602682e-05, 8.31284488e-05,
       8.85214395e-05, 1.07590386e-04, 1.20659308e-04, 1.53318950e-04,
       9.24989799e-05, 5.75474514e-05, 7.02528632e-05, 4.00292047e-05,
       4.64028381e-05, 4.64103578e-05, 6.36314362e-05, 1.29180684e-04,
       1.98911919e-04, 3.74519004e-04, 5.25781768e-04, 8.09720426e-04,
       1.06861617e-03, 9.21198342e-04, 1.56921509e-03, 1.81931176e-03,
       1.67989521e-03, 2.35942053e-03, 2.33879592e-03, 5.88607229e-03,
       7.60489097e-03, 6.18147571e-03, 5.84007660e-03, 2.65281484e-03,
       1.42347906e-03, 1.01576257e-03, 8.81861546e-04, 5.43077418e-04,
       5.16465690e-04, 2.31711383e-04, 2.59865425e-04, 1.55347676e-04,
       2.87124974e-04, 3.82557511e-04, 4.77673282e-04, 1.26403850e-03,
       7.75011024e-04, 1.93968322e-03, 4.98456322e-03, 3.65127577e-03,
       3.35404137e-03, 2.90384376e-03, 4.22344776e-03, 1.01120006e-02,
       5.79398312e-03, 4.72805742e-03, 3.95878078e-03, 3.68809793e-03,
       2.53521395e-03, 1.28966488e-03, 2.27200752e-03, 2.33263453e-03,
       5.28929848e-03, 6.72875205e-03, 8.93528201e-03, 1.89490337e-02,
       2.58259978e-02, 2.61851903e-02, 7.21390769e-02, 1.17869161e-01,
       8.88549760e-02, 1.01062611e-01, 3.90762053e-02, 4.72911820e-02,
       3.25935893e-02, 7.32597634e-02, 1.01223215e-01, 8.51522014e-02,
       1.68709874e-01, 1.21425040e-01, 2.11570069e-01, 1.52770489e-01,
       1.81212619e-01, 4.87702310e-01, 2.89971411e-01, 3.56477737e-01,
       2.21218899e-01, 3.62581581e-01, 2.19801903e-01, 2.26885900e-01,
       1.32539585e-01, 2.36468941e-01, 1.77000538e-01, 2.10527450e-01,
       8.10237154e-02, 1.05810560e-01, 2.14115620e-01, 2.86609918e-01,
       3.49825382e-01, 1.24957517e-01, 2.23436132e-01, 8.67506713e-02,
       2.47818813e-01, 7.77429193e-02, 6.42214417e-02, 3.48965414e-02,
       1.78647544e-02, 1.78657733e-02, 1.05969142e-02, 7.86087848e-03,
       1.75713678e-03, 3.12154996e-03, 2.07757601e-03, 3.87666165e-03,
       3.54084768e-03, 1.05113517e-02, 1.70371141e-02, 3.64057943e-02,
       3.22604664e-02, 3.13726403e-02, 2.02494897e-02, 2.39111967e-02,
       2.17462033e-02, 4.45393696e-02, 4.74649854e-02, 1.99527927e-02,
       2.10458096e-02, 1.44630959e-02, 1.00994989e-01, 1.81424767e-01,
       1.50430664e-01, 1.05745651e-01, 7.77164623e-02, 5.96907809e-02,
       4.50886786e-02, 7.67450035e-02, 3.23384888e-02, 2.25054603e-02,
       1.15671186e-02, 2.03146338e-02, 2.27996334e-02, 8.92152637e-03,
       3.30355577e-03, 1.20749918e-03, 1.67136278e-03, 3.27081769e-03,
       8.95592757e-03, 9.67419054e-03, 9.78299696e-03, 5.89335617e-03,
       2.92186555e-03, 4.70567821e-03, 6.44105254e-03, 1.14317443e-02,
       2.12701666e-03, 1.70642894e-03, 9.27692279e-03, 2.12866366e-02,
       1.72767378e-02, 2.11616326e-02, 3.22333388e-02, 9.15704444e-02,
       3.26557159e-01, 7.79320776e-01, 8.76947761e-01, 5.69033802e-01,
       6.19992673e-01, 6.64458632e-01, 8.24558318e-01, 7.96634614e-01,
       4.61967379e-01, 2.91052699e-01, 9.86434072e-02, 5.70966899e-02,
       3.28147151e-02, 2.42051054e-02, 3.78386751e-02, 6.76693469e-02,
       5.69982715e-02, 5.05505949e-02, 4.36870046e-02, 4.11829390e-02,
       2.00734343e-02, 1.09626064e-02, 8.36692750e-03, 9.71605722e-03,
       2.11678585e-03, 1.71288941e-03, 1.60949898e-03, 8.87605362e-04,
       7.60148221e-04, 1.30920461e-03, 4.37712623e-03, 8.74090008e-03,
       6.56881835e-03, 4.68298467e-03, 9.40069091e-03, 1.52641525e-02,
       2.25468017e-02, 1.30508998e-02, 8.75537284e-03, 4.44540987e-03,
       5.55814710e-03, 1.78515967e-02, 1.50594674e-02, 2.88488362e-02,
       5.48478253e-02, 7.55896717e-02, 4.98306826e-02, 1.91523284e-02,
       1.73970647e-02, 1.75312851e-02, 1.70214456e-02, 1.42874671e-02,
       1.11846738e-02, 1.12037538e-02, 1.51142813e-02, 7.24529568e-03,
       4.90887230e-03, 2.77897087e-03, 4.11750283e-03, 2.38150544e-03,
       1.88370829e-03, 7.01387529e-04])

In [41]:
# Splitting the file into two
 
input_file = "../data/interpro_uniprot_evid_1_2_split/pt_87.fasta"
output_file1 = "../data/interpro_uniprot_evid_1_2_split/pt_87_1.fasta"
output_file2 = "../data/interpro_uniprot_evid_1_2_split/pt_87_2.fasta"

# Read all records
records = list(SeqIO.parse(input_file, "fasta"))

# Sanity check
assert len(records) == 1000, f"Expected 1000 records, found {len(records)}"

# Split
part1 = records[:500]
part2 = records[500:]

# Write outputs
SeqIO.write(part1, output_file1, "fasta")
SeqIO.write(part2, output_file2, "fasta")

print("Split complete!")

Split complete!

---

In [28]:
# ipp.__version__   # check that at least version 7
# mycluster = ipp.Cluster(n = int(os.getenv('SLURM_CPUS_ON_NODE')))
# mycluster.start_cluster_sync()

# c = mycluster.connect_client_sync()
# c.wait_for_engines(n = int(os.getenv('SLURM_CPUS_ON_NODE')))
# c.ids

In [29]:
# dview = c[:]
# dview.block = True

# # Load necessary modules on workers
# dview.execute('import sys, os')
# dview.execute('import pandas as pd')
# dview.execute('import numpy as np')
# dview.execute('import re, subprocess')
# dview.execute('import Bio')
# dview.execute('from adpred import ADpred as adp')

In [ ]:
%%time

# Push PSIPRED output to workers
dview.push(dict( ss_dict=ss_dict ))

# Need a wrapper function because map() only operates on one argument
def wrapper(r):
    seq = str(r.seq)
    prot = adp.protein('x', seq)
    
    # Load horizontal secondary structure data
    prot.second_struct = ss_dict[seq]
    
    # Run ADpred
    prot.predict()
    return (prot.sequence, prot.predictions)


# Run a parallel map, executing the wrapper function on indices 0,...,n-1
lview = c.load_balanced_view()
# Cause execution on main process to wait while tasks sent to workers finish
lview.block = True 
out = lview.map(wrapper, recs)   # Run calculation in parallel
adpred_out = dict(out)

In [18]:
%%time
results = make_pred(recs[0])
results

1/1 [==============================] - 2s 2s/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 36ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 28ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 30ms/step
1/1 [==============================] - 0s 32ms/step
1/1 [==============================] - 0s 30ms/step
1/1 [==============================] - 0s 29ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 30ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 33ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 27ms/step
1/1 [==============================] - 0s 32ms/step
1/1 [==============================] - 0s 41ms/step
1/1 [==============================] - 0s 36ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 28ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 16ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 13ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 17ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 14ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step
1/1 [==============================] - 0s 15ms/step

array([5.61811103e-05, 4.40443437e-05, 6.13181037e-05, 8.26251780e-05,
       2.52670958e-04, 1.78079674e-04, 1.09058812e-04, 1.21632787e-04,
       1.71658932e-04, 1.93006039e-04, 8.04404786e-04, 6.22320047e-04,
       6.45624357e-04, 1.80142326e-03, 5.63441950e-04, 4.95417858e-04,
       3.62068851e-04, 1.36827282e-03, 1.21765968e-03, 1.34220789e-03,
       1.34051521e-03, 1.32528564e-03, 1.82191841e-03, 2.72152107e-03,
       2.81181047e-03, 1.71899411e-03, 6.05565356e-03, 4.46838839e-03,
       1.06152566e-02, 8.11810512e-03, 4.71947761e-03, 3.67023260e-03,
       7.94061285e-04, 2.81579996e-04, 2.09606311e-04, 4.90649196e-04,
       6.99731114e-04, 8.65662529e-04, 2.65891111e-04, 1.42347824e-04,
       9.49105524e-05, 1.07035354e-04, 1.69697712e-04, 2.37224420e-04,
       3.86559317e-04, 1.62812765e-04, 2.11327089e-04, 1.26290659e-04,
       1.67787075e-04, 2.36757114e-04, 1.56015085e-04, 8.74015896e-05,
       2.28480130e-05, 3.43243846e-05, 6.78522483e-05, 8.36226463e-05,
       3.94566559e-05, 5.95931670e-05, 4.62980315e-05, 3.97367658e-05,
       4.93083899e-05, 5.14869716e-05, 8.72031160e-05, 7.23183766e-05,
       1.44333331e-04, 5.64478469e-05, 8.44118986e-05, 1.46116756e-04,
       1.62721510e-04, 1.15046314e-04, 9.50821195e-05, 1.08980021e-04,
       8.53353486e-05, 1.12752314e-04, 2.13860229e-04, 5.68660151e-04,
       6.49486494e-04, 9.82229132e-04, 9.29195492e-04, 2.21419334e-03,
       2.19614315e-03, 2.34463322e-03, 1.66931446e-03, 2.81859329e-03,
       2.22277758e-03, 2.64258403e-03, 1.71065645e-03, 1.19507371e-03,
       1.24042796e-03, 4.86693374e-04, 6.02084328e-04, 4.81191528e-04,
       2.88402080e-04, 1.65984486e-04, 1.08162138e-04, 6.68982830e-05,
       9.69952744e-05, 5.84226000e-05, 5.93061304e-05, 4.52950335e-05,
       2.50761623e-05, 1.63764871e-05, 1.05565587e-05, 5.41910185e-06,
       4.41733573e-06, 7.98497604e-06, 4.05349147e-06, 5.89116826e-06,
       4.93487551e-06, 5.29757426e-06, 5.34986702e-06, 9.50814137e-06,
       9.28854297e-06, 1.36757590e-05, 1.49220932e-05, 1.95012999e-05,
       2.67675186e-05, 2.35698972e-05, 4.64454170e-05, 6.02374312e-05,
       9.15254059e-05, 9.81246703e-05, 1.46757957e-04, 1.47564104e-04,
       2.17565379e-04, 1.65253645e-04, 2.86224094e-04, 4.77045774e-04,
       6.30376220e-04, 7.16255570e-04, 1.72099099e-03, 3.25705181e-03,
       5.75558376e-03, 1.80671569e-02, 2.42072176e-02, 1.07235825e-02,
       3.17780091e-03, 1.24161299e-02, 2.12029237e-02, 2.08170619e-02,
       2.84375101e-02, 6.73773736e-02, 4.26495150e-02, 1.81558393e-02,
       1.08126439e-02, 1.07511207e-02, 9.15801059e-03, 5.18037658e-03,
       1.33418404e-02, 1.50425592e-02, 2.31315605e-02, 5.90064786e-02,
       5.16916104e-02, 3.10915653e-02, 3.25828865e-02, 4.57718186e-02,
       3.44481207e-02, 1.37133403e-02, 1.19383764e-02, 1.24304919e-02,
       7.93610979e-03, 9.95257776e-03, 7.11126672e-03, 3.50021222e-03,
       2.70825182e-03, 8.27273633e-03, 1.51854986e-02, 7.50382710e-03,
       1.41616575e-02, 1.55700548e-02, 1.33665502e-02, 1.73290018e-02,
       4.42877002e-02, 6.21831827e-02, 7.89689720e-02, 8.97298157e-02,
       4.14251536e-02, 4.56861407e-02, 8.83757100e-02, 7.46967718e-02,
       3.59531455e-02, 2.26372480e-02, 2.67630480e-02, 2.01305728e-02,
       1.95214618e-02, 5.11302054e-03, 3.55453347e-03, 2.83014681e-03,
       7.19747692e-03, 1.44683546e-03, 2.67834007e-03, 4.96161403e-03,
       9.89170559e-03, 2.49218103e-02, 2.02076882e-02, 1.99938156e-02,
       3.10971332e-03, 1.15042599e-03, 8.92563257e-04, 1.19848514e-03,
       6.40347193e-04, 1.71774847e-03, 1.12619891e-03, 3.88480694e-04,
       2.74967257e-04, 1.55800270e-04, 5.92537108e-04, 4.61772463e-04,
       6.68680354e-04, 5.16965345e-04, 1.59174111e-03, 2.00172747e-03,
       2.08841427e-03, 4.48988052e-03, 6.17649266e-03, 2.53184754e-02,
       5.19147888e-02, 4.43822704e-02, 9.19683464e-03, 4.74726036e-03,
       6.82793045e-03, 1.02040647e-02, 1.29885776e-02, 1.38236266e-02,
       3.62755284e-02, 1.71849858e-02, 1.68073885e-02, 2.31559463e-02,
       2.36893129e-02, 2.22944375e-02, 1.22363577e-02, 1.31745227e-02,
       7.20905419e-03, 1.57447848e-02, 2.97341365e-02, 1.98536757e-02,
       2.32393760e-02, 3.63483727e-02, 3.39557491e-02, 2.16485094e-02,
       1.95822176e-02, 6.35436643e-03, 1.88244565e-03, 3.14722979e-03,
       1.32226152e-02, 8.19535181e-02, 1.03407830e-01, 9.07846987e-02,
       2.82111228e-01, 2.43924528e-01, 2.87006706e-01, 4.22667444e-01,
       7.75038451e-02, 6.52020574e-02, 1.03608198e-01, 1.30773440e-01,
       2.64621735e-01, 6.43786252e-01, 6.86984718e-01, 4.72592562e-01,
       4.91250157e-01, 3.31106216e-01, 5.83028436e-01, 5.08572221e-01,
       3.99939060e-01, 7.81858087e-01, 3.30206722e-01, 2.59552628e-01,
       1.64704755e-01, 1.23058230e-01, 9.86503288e-02, 7.48383179e-02,
       7.16051459e-02, 2.87445355e-02, 2.20953859e-02, 1.40018957e-02,
       1.00624906e-02, 1.54802147e-02, 1.48643199e-02, 1.14422943e-02,
       7.02414289e-03, 7.23218545e-03, 1.33092580e-02, 1.01809725e-02,
       8.53845477e-03, 1.10535575e-02, 1.46931373e-02, 3.42946406e-03,
       1.95717905e-03, 2.57117138e-03, 5.69262716e-04, 1.25435193e-03,
       2.48762616e-03, 5.48803294e-03, 2.88246595e-03, 2.34658807e-03,
       2.32579652e-03, 5.89164905e-03, 4.58620768e-03, 2.73151509e-03,
       3.82517953e-03, 2.54206592e-03, 2.99400138e-03, 4.10540774e-03,
       8.83944705e-03, 1.15658380e-02, 1.76011659e-02, 7.58586638e-03,
       2.31447257e-02, 8.19829851e-03, 4.68909880e-03, 3.20113963e-03,
       5.80882095e-03, 8.12940206e-03, 5.67068532e-03, 8.59648734e-03,
       5.25064860e-03, 1.14187533e-02, 1.59920435e-02, 1.57730896e-02,
       2.44243853e-02, 2.74151564e-02, 2.16522515e-02, 2.07278561e-02,
       3.58244963e-02, 3.20449658e-02, 3.92256603e-02, 2.02139765e-02,
       2.75539942e-02, 1.33998077e-02, 3.37361358e-02, 1.92136634e-02,
       5.83813600e-02, 1.57295708e-02, 1.37858633e-02, 1.71491206e-02,
       1.99659821e-02, 1.96919274e-02, 9.10245720e-03, 1.36441747e-02,
       7.28625245e-03, 1.31729478e-02, 6.38309587e-03, 5.81268361e-03,
       3.38356290e-03, 2.74460809e-03, 1.80175935e-03, 2.05355790e-03,
       2.95781693e-03, 1.67805795e-03, 2.60634930e-03, 1.59508048e-03,
       2.05748319e-03, 1.32619590e-03, 1.96154858e-03, 1.88171375e-03,
       1.34127226e-03, 1.03795202e-03, 1.02658162e-03, 2.16435804e-03,
       1.13671785e-03, 1.67315232e-03, 3.05251847e-03, 3.62236868e-03,
       2.69677769e-03, 3.17511614e-03, 2.37856945e-03, 2.80271075e-03,
       5.63867250e-03, 8.99837166e-03, 9.32407472e-03, 8.79671611e-03,
       2.20390409e-02, 4.72814292e-02, 3.47489864e-02, 4.93318774e-02,
       7.49026909e-02, 4.71075214e-02, 6.92292154e-02, 4.48154174e-02,
       4.99923155e-02, 5.49971722e-02, 4.36697192e-02, 4.51574139e-02,
       2.76271384e-02, 2.86451802e-02, 6.86819553e-02, 1.32296607e-01,
       3.92436534e-01, 8.84536862e-01, 9.55169439e-01, 9.81697977e-01,
       9.75707114e-01, 9.72314715e-01, 9.69266176e-01, 9.59068835e-01,
       9.83674347e-01, 9.51340616e-01, 8.18836212e-01, 9.44061399e-01,
       9.89248216e-01, 9.64723945e-01, 9.53814030e-01, 9.58867908e-01,
       9.79841232e-01, 9.75438356e-01, 9.70007002e-01, 9.73951519e-01,
       9.89948094e-01, 9.87834573e-01, 9.91446197e-01, 9.95184124e-01,
       9.96123731e-01, 9.95243549e-01, 9.95757520e-01, 9.95203733e-01,
       9.76912975e-01, 6.71569407e-01, 8.59449863e-01, 7.93662071e-01,
       9.09168661e-01, 8.63448143e-01, 8.17195058e-01, 9.12074804e-01,
       9.33545351e-01, 7.78093874e-01, 6.99130416e-01, 5.69104970e-01,
       2.68242925e-01, 2.27257490e-01, 1.05195388e-01, 9.48800445e-02,
       1.45794630e-01, 4.30306047e-02, 2.42351145e-02, 2.90888697e-02,
       3.73308361e-02, 1.79298352e-02, 5.53670013e-03, 3.70620308e-03,
       1.24177011e-03, 1.47065800e-03, 1.21214602e-03, 1.21224381e-03,
       5.95671823e-04, 9.13282274e-04, 4.50852036e-04, 5.18259476e-04,
       3.01389751e-04, 5.78111329e-04, 4.28554078e-04, 1.53774861e-04,
       2.32443374e-04, 1.73973574e-04, 2.00682829e-04, 2.22850649e-04,
       2.64057511e-04, 2.74337188e-04, 1.18131971e-03, 1.12850573e-02,
       5.16108796e-02, 1.85584232e-01, 3.10699672e-01, 7.40526319e-01,
       7.40705132e-01, 5.87117195e-01, 3.90864909e-01, 2.14571044e-01,
       1.51407421e-01, 1.86999977e-01, 2.10557982e-01, 2.28639320e-01,
       3.69525224e-01, 4.79246825e-01, 7.18161106e-01, 7.49973416e-01,
       3.73892576e-01, 3.25154006e-01, 2.34370366e-01, 2.23677233e-01,
       2.29690909e-01, 1.66261837e-01, 1.60271421e-01, 1.41466826e-01,
       1.10778488e-01, 1.81407690e-01, 2.59717494e-01, 3.75129163e-01,
       3.03721517e-01, 1.91456899e-01, 2.87836373e-01, 1.28289074e-01,
       1.09049685e-01, 1.33849964e-01, 1.65423527e-01, 1.75298259e-01,
       1.04039885e-01, 6.66983873e-02, 5.42284623e-02])

In [23]:
dict([("seq", results), ("seq2", results)])

{'seq': array([5.61811103e-05, 4.40443437e-05, 6.13181037e-05, 8.26251780e-05,
        2.52670958e-04, 1.78079674e-04, 1.09058812e-04, 1.21632787e-04,
        1.71658932e-04, 1.93006039e-04, 8.04404786e-04, 6.22320047e-04,
        6.45624357e-04, 1.80142326e-03, 5.63441950e-04, 4.95417858e-04,
        3.62068851e-04, 1.36827282e-03, 1.21765968e-03, 1.34220789e-03,
        1.34051521e-03, 1.32528564e-03, 1.82191841e-03, 2.72152107e-03,
        2.81181047e-03, 1.71899411e-03, 6.05565356e-03, 4.46838839e-03,
        1.06152566e-02, 8.11810512e-03, 4.71947761e-03, 3.67023260e-03,
        7.94061285e-04, 2.81579996e-04, 2.09606311e-04, 4.90649196e-04,
        6.99731114e-04, 8.65662529e-04, 2.65891111e-04, 1.42347824e-04,
        9.49105524e-05, 1.07035354e-04, 1.69697712e-04, 2.37224420e-04,
        3.86559317e-04, 1.62812765e-04, 2.11327089e-04, 1.26290659e-04,
        1.67787075e-04, 2.36757114e-04, 1.56015085e-04, 8.74015896e-05,
        2.28480130e-05, 3.43243846e-05, 6.78522483e-05, 8.36226463e-05,
        3.94566559e-05, 5.95931670e-05, 4.62980315e-05, 3.97367658e-05,
        4.93083899e-05, 5.14869716e-05, 8.72031160e-05, 7.23183766e-05,
        1.44333331e-04, 5.64478469e-05, 8.44118986e-05, 1.46116756e-04,
        1.62721510e-04, 1.15046314e-04, 9.50821195e-05, 1.08980021e-04,
        8.53353486e-05, 1.12752314e-04, 2.13860229e-04, 5.68660151e-04,
        6.49486494e-04, 9.82229132e-04, 9.29195492e-04, 2.21419334e-03,
        2.19614315e-03, 2.34463322e-03, 1.66931446e-03, 2.81859329e-03,
        2.22277758e-03, 2.64258403e-03, 1.71065645e-03, 1.19507371e-03,
        1.24042796e-03, 4.86693374e-04, 6.02084328e-04, 4.81191528e-04,
        2.88402080e-04, 1.65984486e-04, 1.08162138e-04, 6.68982830e-05,
        9.69952744e-05, 5.84226000e-05, 5.93061304e-05, 4.52950335e-05,
        2.50761623e-05, 1.63764871e-05, 1.05565587e-05, 5.41910185e-06,
        4.41733573e-06, 7.98497604e-06, 4.05349147e-06, 5.89116826e-06,
        4.93487551e-06, 5.29757426e-06, 5.34986702e-06, 9.50814137e-06,
        9.28854297e-06, 1.36757590e-05, 1.49220932e-05, 1.95012999e-05,
        2.67675186e-05, 2.35698972e-05, 4.64454170e-05, 6.02374312e-05,
        9.15254059e-05, 9.81246703e-05, 1.46757957e-04, 1.47564104e-04,
        2.17565379e-04, 1.65253645e-04, 2.86224094e-04, 4.77045774e-04,
        6.30376220e-04, 7.16255570e-04, 1.72099099e-03, 3.25705181e-03,
        5.75558376e-03, 1.80671569e-02, 2.42072176e-02, 1.07235825e-02,
        3.17780091e-03, 1.24161299e-02, 2.12029237e-02, 2.08170619e-02,
        2.84375101e-02, 6.73773736e-02, 4.26495150e-02, 1.81558393e-02,
        1.08126439e-02, 1.07511207e-02, 9.15801059e-03, 5.18037658e-03,
        1.33418404e-02, 1.50425592e-02, 2.31315605e-02, 5.90064786e-02,
        5.16916104e-02, 3.10915653e-02, 3.25828865e-02, 4.57718186e-02,
        3.44481207e-02, 1.37133403e-02, 1.19383764e-02, 1.24304919e-02,
        7.93610979e-03, 9.95257776e-03, 7.11126672e-03, 3.50021222e-03,
        2.70825182e-03, 8.27273633e-03, 1.51854986e-02, 7.50382710e-03,
        1.41616575e-02, 1.55700548e-02, 1.33665502e-02, 1.73290018e-02,
        4.42877002e-02, 6.21831827e-02, 7.89689720e-02, 8.97298157e-02,
        4.14251536e-02, 4.56861407e-02, 8.83757100e-02, 7.46967718e-02,
        3.59531455e-02, 2.26372480e-02, 2.67630480e-02, 2.01305728e-02,
        1.95214618e-02, 5.11302054e-03, 3.55453347e-03, 2.83014681e-03,
        7.19747692e-03, 1.44683546e-03, 2.67834007e-03, 4.96161403e-03,
        9.89170559e-03, 2.49218103e-02, 2.02076882e-02, 1.99938156e-02,
        3.10971332e-03, 1.15042599e-03, 8.92563257e-04, 1.19848514e-03,
        6.40347193e-04, 1.71774847e-03, 1.12619891e-03, 3.88480694e-04,
        2.74967257e-04, 1.55800270e-04, 5.92537108e-04, 4.61772463e-04,
        6.68680354e-04, 5.16965345e-04, 1.59174111e-03, 2.00172747e-03,
        2.08841427e-03, 4.48988052e-03, 6.17649266e-03, 2.53184754e-02,
        5.19147888e-02, 4.43822704e-02, 9.19683464e-03, 4.74726036e-03,
        6.82793045e-03, 1.02040647e-02, 1.29885776e-02, 1.38236266e-02,
        3.62755284e-02, 1.71849858e-02, 1.68073885e-02, 2.31559463e-02,
        2.36893129e-02, 2.22944375e-02, 1.22363577e-02, 1.31745227e-02,
        7.20905419e-03, 1.57447848e-02, 2.97341365e-02, 1.98536757e-02,
        2.32393760e-02, 3.63483727e-02, 3.39557491e-02, 2.16485094e-02,
        1.95822176e-02, 6.35436643e-03, 1.88244565e-03, 3.14722979e-03,
        1.32226152e-02, 8.19535181e-02, 1.03407830e-01, 9.07846987e-02,
        2.82111228e-01, 2.43924528e-01, 2.87006706e-01, 4.22667444e-01,
        7.75038451e-02, 6.52020574e-02, 1.03608198e-01, 1.30773440e-01,
        2.64621735e-01, 6.43786252e-01, 6.86984718e-01, 4.72592562e-01,
        4.91250157e-01, 3.31106216e-01, 5.83028436e-01, 5.08572221e-01,
        3.99939060e-01, 7.81858087e-01, 3.30206722e-01, 2.59552628e-01,
        1.64704755e-01, 1.23058230e-01, 9.86503288e-02, 7.48383179e-02,
        7.16051459e-02, 2.87445355e-02, 2.20953859e-02, 1.40018957e-02,
        1.00624906e-02, 1.54802147e-02, 1.48643199e-02, 1.14422943e-02,
        7.02414289e-03, 7.23218545e-03, 1.33092580e-02, 1.01809725e-02,
        8.53845477e-03, 1.10535575e-02, 1.46931373e-02, 3.42946406e-03,
        1.95717905e-03, 2.57117138e-03, 5.69262716e-04, 1.25435193e-03,
        2.48762616e-03, 5.48803294e-03, 2.88246595e-03, 2.34658807e-03,
        2.32579652e-03, 5.89164905e-03, 4.58620768e-03, 2.73151509e-03,
        3.82517953e-03, 2.54206592e-03, 2.99400138e-03, 4.10540774e-03,
        8.83944705e-03, 1.15658380e-02, 1.76011659e-02, 7.58586638e-03,
        2.31447257e-02, 8.19829851e-03, 4.68909880e-03, 3.20113963e-03,
        5.80882095e-03, 8.12940206e-03, 5.67068532e-03, 8.59648734e-03,
        5.25064860e-03, 1.14187533e-02, 1.59920435e-02, 1.57730896e-02,
        2.44243853e-02, 2.74151564e-02, 2.16522515e-02, 2.07278561e-02,
        3.58244963e-02, 3.20449658e-02, 3.92256603e-02, 2.02139765e-02,
        2.75539942e-02, 1.33998077e-02, 3.37361358e-02, 1.92136634e-02,
        5.83813600e-02, 1.57295708e-02, 1.37858633e-02, 1.71491206e-02,
        1.99659821e-02, 1.96919274e-02, 9.10245720e-03, 1.36441747e-02,
        7.28625245e-03, 1.31729478e-02, 6.38309587e-03, 5.81268361e-03,
        3.38356290e-03, 2.74460809e-03, 1.80175935e-03, 2.05355790e-03,
        2.95781693e-03, 1.67805795e-03, 2.60634930e-03, 1.59508048e-03,
        2.05748319e-03, 1.32619590e-03, 1.96154858e-03, 1.88171375e-03,
        1.34127226e-03, 1.03795202e-03, 1.02658162e-03, 2.16435804e-03,
        1.13671785e-03, 1.67315232e-03, 3.05251847e-03, 3.62236868e-03,
        2.69677769e-03, 3.17511614e-03, 2.37856945e-03, 2.80271075e-03,
        5.63867250e-03, 8.99837166e-03, 9.32407472e-03, 8.79671611e-03,
        2.20390409e-02, 4.72814292e-02, 3.47489864e-02, 4.93318774e-02,
        7.49026909e-02, 4.71075214e-02, 6.92292154e-02, 4.48154174e-02,
        4.99923155e-02, 5.49971722e-02, 4.36697192e-02, 4.51574139e-02,
        2.76271384e-02, 2.86451802e-02, 6.86819553e-02, 1.32296607e-01,
        3.92436534e-01, 8.84536862e-01, 9.55169439e-01, 9.81697977e-01,
        9.75707114e-01, 9.72314715e-01, 9.69266176e-01, 9.59068835e-01,
        9.83674347e-01, 9.51340616e-01, 8.18836212e-01, 9.44061399e-01,
        9.89248216e-01, 9.64723945e-01, 9.53814030e-01, 9.58867908e-01,
        9.79841232e-01, 9.75438356e-01, 9.70007002e-01, 9.73951519e-01,
        9.89948094e-01, 9.87834573e-01, 9.91446197e-01, 9.95184124e-01,
        9.96123731e-01, 9.95243549e-01, 9.95757520e-01, 9.95203733e-01,
        9.76912975e-01, 6.71569407e-01, 8.59449863e-01, 7.93662071e-01,
        9.09168661e-01, 8.63448143e-01, 8.17195058e-01, 9.12074804e-01,
        9.33545351e-01, 7.78093874e-01, 6.99130416e-01, 5.69104970e-01,
        2.68242925e-01, 2.27257490e-01, 1.05195388e-01, 9.48800445e-02,
        1.45794630e-01, 4.30306047e-02, 2.42351145e-02, 2.90888697e-02,
        3.73308361e-02, 1.79298352e-02, 5.53670013e-03, 3.70620308e-03,
        1.24177011e-03, 1.47065800e-03, 1.21214602e-03, 1.21224381e-03,
        5.95671823e-04, 9.13282274e-04, 4.50852036e-04, 5.18259476e-04,
        3.01389751e-04, 5.78111329e-04, 4.28554078e-04, 1.53774861e-04,
        2.32443374e-04, 1.73973574e-04, 2.00682829e-04, 2.22850649e-04,
        2.64057511e-04, 2.74337188e-04, 1.18131971e-03, 1.12850573e-02,
        5.16108796e-02, 1.85584232e-01, 3.10699672e-01, 7.40526319e-01,
        7.40705132e-01, 5.87117195e-01, 3.90864909e-01, 2.14571044e-01,
        1.51407421e-01, 1.86999977e-01, 2.10557982e-01, 2.28639320e-01,
        3.69525224e-01, 4.79246825e-01, 7.18161106e-01, 7.49973416e-01,
        3.73892576e-01, 3.25154006e-01, 2.34370366e-01, 2.23677233e-01,
        2.29690909e-01, 1.66261837e-01, 1.60271421e-01, 1.41466826e-01,
        1.10778488e-01, 1.81407690e-01, 2.59717494e-01, 3.75129163e-01,
        3.03721517e-01, 1.91456899e-01, 2.87836373e-01, 1.28289074e-01,
        1.09049685e-01, 1.33849964e-01, 1.65423527e-01, 1.75298259e-01,
        1.04039885e-01, 6.66983873e-02, 5.42284623e-02]),
 'seq2': array([5.61811103e-05, 4.40443437e-05, 6.13181037e-05, 8.26251780e-05,
        2.52670958e-04, 1.78079674e-04, 1.09058812e-04, 1.21632787e-04,
        1.71658932e-04, 1.93006039e-04, 8.04404786e-04, 6.22320047e-04,
        6.45624357e-04, 1.80142326e-03, 5.63441950e-04, 4.95417858e-04,
        3.62068851e-04, 1.36827282e-03, 1.21765968e-03, 1.34220789e-03,
        1.34051521e-03, 1.32528564e-03, 1.82191841e-03, 2.72152107e-03,
        2.81181047e-03, 1.71899411e-03, 6.05565356e-03, 4.46838839e-03,
        1.06152566e-02, 8.11810512e-03, 4.71947761e-03, 3.67023260e-03,
        7.94061285e-04, 2.81579996e-04, 2.09606311e-04, 4.90649196e-04,
        6.99731114e-04, 8.65662529e-04, 2.65891111e-04, 1.42347824e-04,
        9.49105524e-05, 1.07035354e-04, 1.69697712e-04, 2.37224420e-04,
        3.86559317e-04, 1.62812765e-04, 2.11327089e-04, 1.26290659e-04,
        1.67787075e-04, 2.36757114e-04, 1.56015085e-04, 8.74015896e-05,
        2.28480130e-05, 3.43243846e-05, 6.78522483e-05, 8.36226463e-05,
        3.94566559e-05, 5.95931670e-05, 4.62980315e-05, 3.97367658e-05,
        4.93083899e-05, 5.14869716e-05, 8.72031160e-05, 7.23183766e-05,
        1.44333331e-04, 5.64478469e-05, 8.44118986e-05, 1.46116756e-04,
        1.62721510e-04, 1.15046314e-04, 9.50821195e-05, 1.08980021e-04,
        8.53353486e-05, 1.12752314e-04, 2.13860229e-04, 5.68660151e-04,
        6.49486494e-04, 9.82229132e-04, 9.29195492e-04, 2.21419334e-03,
        2.19614315e-03, 2.34463322e-03, 1.66931446e-03, 2.81859329e-03,
        2.22277758e-03, 2.64258403e-03, 1.71065645e-03, 1.19507371e-03,
        1.24042796e-03, 4.86693374e-04, 6.02084328e-04, 4.81191528e-04,
        2.88402080e-04, 1.65984486e-04, 1.08162138e-04, 6.68982830e-05,
        9.69952744e-05, 5.84226000e-05, 5.93061304e-05, 4.52950335e-05,
        2.50761623e-05, 1.63764871e-05, 1.05565587e-05, 5.41910185e-06,
        4.41733573e-06, 7.98497604e-06, 4.05349147e-06, 5.89116826e-06,
        4.93487551e-06, 5.29757426e-06, 5.34986702e-06, 9.50814137e-06,
        9.28854297e-06, 1.36757590e-05, 1.49220932e-05, 1.95012999e-05,
        2.67675186e-05, 2.35698972e-05, 4.64454170e-05, 6.02374312e-05,
        9.15254059e-05, 9.81246703e-05, 1.46757957e-04, 1.47564104e-04,
        2.17565379e-04, 1.65253645e-04, 2.86224094e-04, 4.77045774e-04,
        6.30376220e-04, 7.16255570e-04, 1.72099099e-03, 3.25705181e-03,
        5.75558376e-03, 1.80671569e-02, 2.42072176e-02, 1.07235825e-02,
        3.17780091e-03, 1.24161299e-02, 2.12029237e-02, 2.08170619e-02,
        2.84375101e-02, 6.73773736e-02, 4.26495150e-02, 1.81558393e-02,
        1.08126439e-02, 1.07511207e-02, 9.15801059e-03, 5.18037658e-03,
        1.33418404e-02, 1.50425592e-02, 2.31315605e-02, 5.90064786e-02,
        5.16916104e-02, 3.10915653e-02, 3.25828865e-02, 4.57718186e-02,
        3.44481207e-02, 1.37133403e-02, 1.19383764e-02, 1.24304919e-02,
        7.93610979e-03, 9.95257776e-03, 7.11126672e-03, 3.50021222e-03,
        2.70825182e-03, 8.27273633e-03, 1.51854986e-02, 7.50382710e-03,
        1.41616575e-02, 1.55700548e-02, 1.33665502e-02, 1.73290018e-02,
        4.42877002e-02, 6.21831827e-02, 7.89689720e-02, 8.97298157e-02,
        4.14251536e-02, 4.56861407e-02, 8.83757100e-02, 7.46967718e-02,
        3.59531455e-02, 2.26372480e-02, 2.67630480e-02, 2.01305728e-02,
        1.95214618e-02, 5.11302054e-03, 3.55453347e-03, 2.83014681e-03,
        7.19747692e-03, 1.44683546e-03, 2.67834007e-03, 4.96161403e-03,
        9.89170559e-03, 2.49218103e-02, 2.02076882e-02, 1.99938156e-02,
        3.10971332e-03, 1.15042599e-03, 8.92563257e-04, 1.19848514e-03,
        6.40347193e-04, 1.71774847e-03, 1.12619891e-03, 3.88480694e-04,
        2.74967257e-04, 1.55800270e-04, 5.92537108e-04, 4.61772463e-04,
        6.68680354e-04, 5.16965345e-04, 1.59174111e-03, 2.00172747e-03,
        2.08841427e-03, 4.48988052e-03, 6.17649266e-03, 2.53184754e-02,
        5.19147888e-02, 4.43822704e-02, 9.19683464e-03, 4.74726036e-03,
        6.82793045e-03, 1.02040647e-02, 1.29885776e-02, 1.38236266e-02,
        3.62755284e-02, 1.71849858e-02, 1.68073885e-02, 2.31559463e-02,
        2.36893129e-02, 2.22944375e-02, 1.22363577e-02, 1.31745227e-02,
        7.20905419e-03, 1.57447848e-02, 2.97341365e-02, 1.98536757e-02,
        2.32393760e-02, 3.63483727e-02, 3.39557491e-02, 2.16485094e-02,
        1.95822176e-02, 6.35436643e-03, 1.88244565e-03, 3.14722979e-03,
        1.32226152e-02, 8.19535181e-02, 1.03407830e-01, 9.07846987e-02,
        2.82111228e-01, 2.43924528e-01, 2.87006706e-01, 4.22667444e-01,
        7.75038451e-02, 6.52020574e-02, 1.03608198e-01, 1.30773440e-01,
        2.64621735e-01, 6.43786252e-01, 6.86984718e-01, 4.72592562e-01,
        4.91250157e-01, 3.31106216e-01, 5.83028436e-01, 5.08572221e-01,
        3.99939060e-01, 7.81858087e-01, 3.30206722e-01, 2.59552628e-01,
        1.64704755e-01, 1.23058230e-01, 9.86503288e-02, 7.48383179e-02,
        7.16051459e-02, 2.87445355e-02, 2.20953859e-02, 1.40018957e-02,
        1.00624906e-02, 1.54802147e-02, 1.48643199e-02, 1.14422943e-02,
        7.02414289e-03, 7.23218545e-03, 1.33092580e-02, 1.01809725e-02,
        8.53845477e-03, 1.10535575e-02, 1.46931373e-02, 3.42946406e-03,
        1.95717905e-03, 2.57117138e-03, 5.69262716e-04, 1.25435193e-03,
        2.48762616e-03, 5.48803294e-03, 2.88246595e-03, 2.34658807e-03,
        2.32579652e-03, 5.89164905e-03, 4.58620768e-03, 2.73151509e-03,
        3.82517953e-03, 2.54206592e-03, 2.99400138e-03, 4.10540774e-03,
        8.83944705e-03, 1.15658380e-02, 1.76011659e-02, 7.58586638e-03,
        2.31447257e-02, 8.19829851e-03, 4.68909880e-03, 3.20113963e-03,
        5.80882095e-03, 8.12940206e-03, 5.67068532e-03, 8.59648734e-03,
        5.25064860e-03, 1.14187533e-02, 1.59920435e-02, 1.57730896e-02,
        2.44243853e-02, 2.74151564e-02, 2.16522515e-02, 2.07278561e-02,
        3.58244963e-02, 3.20449658e-02, 3.92256603e-02, 2.02139765e-02,
        2.75539942e-02, 1.33998077e-02, 3.37361358e-02, 1.92136634e-02,
        5.83813600e-02, 1.57295708e-02, 1.37858633e-02, 1.71491206e-02,
        1.99659821e-02, 1.96919274e-02, 9.10245720e-03, 1.36441747e-02,
        7.28625245e-03, 1.31729478e-02, 6.38309587e-03, 5.81268361e-03,
        3.38356290e-03, 2.74460809e-03, 1.80175935e-03, 2.05355790e-03,
        2.95781693e-03, 1.67805795e-03, 2.60634930e-03, 1.59508048e-03,
        2.05748319e-03, 1.32619590e-03, 1.96154858e-03, 1.88171375e-03,
        1.34127226e-03, 1.03795202e-03, 1.02658162e-03, 2.16435804e-03,
        1.13671785e-03, 1.67315232e-03, 3.05251847e-03, 3.62236868e-03,
        2.69677769e-03, 3.17511614e-03, 2.37856945e-03, 2.80271075e-03,
        5.63867250e-03, 8.99837166e-03, 9.32407472e-03, 8.79671611e-03,
        2.20390409e-02, 4.72814292e-02, 3.47489864e-02, 4.93318774e-02,
        7.49026909e-02, 4.71075214e-02, 6.92292154e-02, 4.48154174e-02,
        4.99923155e-02, 5.49971722e-02, 4.36697192e-02, 4.51574139e-02,
        2.76271384e-02, 2.86451802e-02, 6.86819553e-02, 1.32296607e-01,
        3.92436534e-01, 8.84536862e-01, 9.55169439e-01, 9.81697977e-01,
        9.75707114e-01, 9.72314715e-01, 9.69266176e-01, 9.59068835e-01,
        9.83674347e-01, 9.51340616e-01, 8.18836212e-01, 9.44061399e-01,
        9.89248216e-01, 9.64723945e-01, 9.53814030e-01, 9.58867908e-01,
        9.79841232e-01, 9.75438356e-01, 9.70007002e-01, 9.73951519e-01,
        9.89948094e-01, 9.87834573e-01, 9.91446197e-01, 9.95184124e-01,
        9.96123731e-01, 9.95243549e-01, 9.95757520e-01, 9.95203733e-01,
        9.76912975e-01, 6.71569407e-01, 8.59449863e-01, 7.93662071e-01,
        9.09168661e-01, 8.63448143e-01, 8.17195058e-01, 9.12074804e-01,
        9.33545351e-01, 7.78093874e-01, 6.99130416e-01, 5.69104970e-01,
        2.68242925e-01, 2.27257490e-01, 1.05195388e-01, 9.48800445e-02,
        1.45794630e-01, 4.30306047e-02, 2.42351145e-02, 2.90888697e-02,
        3.73308361e-02, 1.79298352e-02, 5.53670013e-03, 3.70620308e-03,
        1.24177011e-03, 1.47065800e-03, 1.21214602e-03, 1.21224381e-03,
        5.95671823e-04, 9.13282274e-04, 4.50852036e-04, 5.18259476e-04,
        3.01389751e-04, 5.78111329e-04, 4.28554078e-04, 1.53774861e-04,
        2.32443374e-04, 1.73973574e-04, 2.00682829e-04, 2.22850649e-04,
        2.64057511e-04, 2.74337188e-04, 1.18131971e-03, 1.12850573e-02,
        5.16108796e-02, 1.85584232e-01, 3.10699672e-01, 7.40526319e-01,
        7.40705132e-01, 5.87117195e-01, 3.90864909e-01, 2.14571044e-01,
        1.51407421e-01, 1.86999977e-01, 2.10557982e-01, 2.28639320e-01,
        3.69525224e-01, 4.79246825e-01, 7.18161106e-01, 7.49973416e-01,
        3.73892576e-01, 3.25154006e-01, 2.34370366e-01, 2.23677233e-01,
        2.29690909e-01, 1.66261837e-01, 1.60271421e-01, 1.41466826e-01,
        1.10778488e-01, 1.81407690e-01, 2.59717494e-01, 3.75129163e-01,
        3.03721517e-01, 1.91456899e-01, 2.87836373e-01, 1.28289074e-01,
        1.09049685e-01, 1.33849964e-01, 1.65423527e-01, 1.75298259e-01,
        1.04039885e-01, 6.66983873e-02, 5.42284623e-02])}

In [ ]:
adpred_ss =