In [59]:
import pandas as pd
import numpy as np
import protfasta

# Compiling test sequences
Plan: 
- ARF
- Pdr1
- Sanborn non nuclear human TFs

In [91]:
arf_scores = pd.read_csv("../data/arf_scores_NIHMS2033317-supplement-Table_S3.csv")
arf_scores = arf_scores.rename(columns = {"Fragment Sequence" : "protein sequence"})
arf_scores["id"] = "arf" + "_" + arf_scores["Model"] + "_" + arf_scores["Start Position"].astype(str)
arf_scores

,ARF Clade,Clade A ARF Subclade,Species,Model,Start Position,protein sequence,ScaleScore,id
0,Clade C,NaN,Amborella trichopododa,evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_27.mo...,1,VVSTIPSVQLTAFSPAKKKLRLSPHLDFPIDSTFHPLSSN,0.132163,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...
1,Clade C,NaN,Amborella trichopododa,evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_27.mo...,11,TAFSPAKKKLRLSPHLDFPIDSTFHPLSSNIDPTFASLSS,0.698559,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...
2,Clade C,NaN,Amborella trichopododa,evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_27.mo...,21,RLSPHLDFPIDSTFHPLSSNIDPTFASLSSNLNPTPLTSS,1.002289,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...
3,Clade C,NaN,Amborella trichopododa,evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_27.mo...,31,DSTFHPLSSNIDPTFASLSSNLNPTPLTSSMPRPTNPFQG,0.216912,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...
4,Clade C,NaN,Amborella trichopododa,evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_27.mo...,41,IDPTFASLSSNLNPTPLTSSMPRPTNPFQGLPDYHVPAGI,-0.182901,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...
...,...,...,...,...,...,...,...,...
9538,NaN,NaN,Arabidopsis thaliana,ARF7_AD2_DEtoA,1,GANNRQQNFLAPTFGLAGASRNSLLGGANVANGFVPATLL,-0.119703,arf_ARF7_AD2_DEtoA_1
9539,NaN,NaN,Arabidopsis thaliana,ARF19_AD1_minusswapplus,1,PPFFDPEYPDQPGMPRRKLRMKNAFEDAMPWMGKRFGMER,-0.348388,arf_ARF19_AD1_minusswapplus_1
9540,NaN,NaN,Arabidopsis thaliana,ARF19_AD2_minusswapplus,1,SQLQQQSMLPTGAEMTHQNINSMGNEGLSQMTSFAQKMQF,-0.758803,arf_ARF19_AD2_minusswapplus_1
9541,NaN,NaN,Arabidopsis thaliana,ARF7_AD1_minusswapplus,1,PPFFDPDFSGQPGMPRRKTRMKSALEDAMPWLRNSLKMER,-0.394609,arf_ARF7_AD1_minusswapplus_1
9542,NaN,NaN,Arabidopsis thaliana,ARF7_AD2_minusswapplus,1,GKNNDQQNFLAPTFGLRGRSDNSLLGGANVRNGFVPRTLL,6.414306,arf_ARF7_AD2_minusswapplus_1

In [88]:
mutants = pd.read_csv("../data/53 aa mutants, see Fig 2,4,7-Table 1.csv")
short_mutants = pd.read_csv("../data/cAD muts and 9mers, see Fig 3,4-Table 1.csv")
nuclear = pd.read_csv("../data/Nuclear proteins, see Fig 7-Table 1.csv")
all_sanborn = pd.concat([mutants, short_mutants, nuclear])
all_sanborn["id"] = "sanborn" + "_" + all_sanborn["Unnamed: 0"]
all_sanborn

,Unnamed: 0,protein sequence,protein,protein ID,position,activation,Z score,group,num cells,"num cells, bin 1",...,"num cells, bin 4","num cells, bin 5","num cells, bin 6","num cells, bin 7","num cells, bin 8",GFP average,GFP std,nuclear confident,disorder fraction,id
0,D_ADbest-AA-muts_P07248_415_DE,SENQPEFVEFQELLENETLGNELLETTAVLKEFELLHEESVSATAT...,ADR1,P07248,415.0,16.93,4.55,ADbest-AA-muts,39.11,0.00,...,4.21,21.40,13.50,0.00,0.00,188.37,1.95,NaN,NaN,sanborn_D_ADbest-AA-muts_P07248_415_DE
1,D_ADbest-AA-muts_P07248_415_ED,SDNQPDFVDFQDLLDNDTLGNDLLDTTAVLKDFDLLHDDSVSATAT...,ADR1,P07248,415.0,57.47,6.51,ADbest-AA-muts,138.03,0.00,...,2.11,5.60,60.25,56.48,13.59,639.38,2.01,NaN,NaN,sanborn_D_ADbest-AA-muts_P07248_415_ED
2,D_ADbest-AA-muts_P07248_648_DE,LPHFPIIHPSLLELELESLQRYTNEEGYEEAENAQLFERLSQGTEK...,ADR1,P07248,648.0,8.77,3.49,ADbest-AA-muts,53.53,0.00,...,17.37,33.63,0.96,0.00,0.00,97.59,1.97,NaN,NaN,sanborn_D_ADbest-AA-muts_P07248_648_DE
3,D_ADbest-AA-muts_P07248_648_ED,LPHFPIIHPSLLDLDLDSLQRYTNDDGYDDADNAQLFDRLSQGTDK...,ADR1,P07248,648.0,18.60,4.70,ADbest-AA-muts,163.68,0.00,...,14.21,67.25,73.26,3.70,0.00,206.91,2.37,NaN,NaN,sanborn_D_ADbest-AA-muts_P07248_648_ED
4,D_ADbest-AA-muts_P07269_0_DE,MMEEFSYEHEFNTHFATELEYLQHEQQQQQQQQHEQQHNQQQQPQP...,PHO2,P07269,0.0,9.11,3.55,ADbest-AA-muts,57.21,0.00,...,16.32,39.23,0.00,0.00,0.00,101.40,1.82,NaN,NaN,sanborn_D_ADbest-AA-muts_P07269_0_DE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2066,D_nuc-nonhits_Q03656_575,LLGAPWGCGADIWSTACLIFELITGDFLFEPDEGHSYTKDDDHIAQ...,SKY1,Q03656,575.0,0.88,-0.20,nuc-nonhits,373.27,15.28,...,2.63,0.00,0.00,0.00,0.00,9.82,1.70,False,0.05,sanborn_D_nuc-nonhits_Q03656_575
2067,D_nuc-nonhits_P17883_860,QVLRLFIWIESKVDTLPVESLVSIFENSQFSGSEEIDSVDNIKIDT...,SKI3,P17883,860.0,0.87,-0.22,nuc-nonhits,123.59,10.74,...,0.00,0.00,0.00,0.00,0.00,9.71,1.81,False,0.11,sanborn_D_nuc-nonhits_P17883_860
2068,D_nuc-nonhits_P53036_375,QRDPVYLGHLLYELTMHMEDFYALLIKLENDDDDDHDTASKALPSV...,SAP4,P53036,375.0,0.87,-0.22,nuc-nonhits,198.28,6.64,...,8.42,0.00,0.00,0.00,0.00,9.68,1.79,False,0.27,sanborn_D_nuc-nonhits_P53036_375
2069,D_nuc-nonhits_P22211_487,EYCIGTTLNHPNIIETIEIVYENDRILQVMEYCEYDLFAIVMSNKM...,NPR1,P22211,487.0,0.84,-0.29,nuc-nonhits,144.75,12.74,...,0.00,0.00,0.00,0.00,0.00,9.31,1.80,False,0.01,sanborn_D_nuc-nonhits_P22211_487
2070,D_nuc-nonhits_P38217_700,CLQDPVHEVRQSCFALLGDIVYFFNSELVIGNLEDFLKLIGTEIMH...,KAP104,P38217,700.0,0.68,-0.61,nuc-nonhits,188.44,51.18,...,4.74,0.00,0.48,0.00,0.00,7.60,2.29,False,0.05,sanborn_D_nuc-nonhits_P38217_700

In [93]:
test_seqs = pd.concat([arf_scores[["protein sequence", "id"]], all_sanborn[["protein sequence", "id"]]])
test_seqs = test_seqs.drop_duplicates()
test_seqs["group"] = "test"
test_seqs

,protein sequence,id,group
0,VVSTIPSVQLTAFSPAKKKLRLSPHLDFPIDSTFHPLSSN,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
1,TAFSPAKKKLRLSPHLDFPIDSTFHPLSSNIDPTFASLSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
2,RLSPHLDFPIDSTFHPLSSNIDPTFASLSSNLNPTPLTSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
3,DSTFHPLSSNIDPTFASLSSNLNPTPLTSSMPRPTNPFQG,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
4,IDPTFASLSSNLNPTPLTSSMPRPTNPFQGLPDYHVPAGI,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
...,...,...,...
2066,LLGAPWGCGADIWSTACLIFELITGDFLFEPDEGHSYTKDDDHIAQ...,sanborn_D_nuc-nonhits_Q03656_575,test
2067,QVLRLFIWIESKVDTLPVESLVSIFENSQFSGSEEIDSVDNIKIDT...,sanborn_D_nuc-nonhits_P17883_860,test
2068,QRDPVYLGHLLYELTMHMEDFYALLIKLENDDDDDHDTASKALPSV...,sanborn_D_nuc-nonhits_P53036_375,test
2069,EYCIGTTLNHPNIIETIEIVYENDRILQVMEYCEYDLFAIVMSNKM...,sanborn_D_nuc-nonhits_P22211_487,test
2070,CLQDPVHEVRQSCFALLGDIVYFFNSELVIGNLEDFLKLIGTEIMH...,sanborn_D_nuc-nonhits_P38217_700,test

In [74]:
# Clustered by mmseqs >70% seq ident
# Disorder threshold
# Length threshold 
train_seqs = protfasta.read_fasta("../data/CL_SK_plant_seqs_disord_thresh.fasta")
train_seqs = pd.DataFrame({"id" : train_seqs.keys(), "protein sequence" : train_seqs.values()}).drop_duplicates()
train_seqs

,id,protein sequence
0,tr|A0A0B4K6B8|A0A0B4K6B8_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
1,tr|A0A0B4K7A6|A0A0B4K7A6_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
2,sp|A0A5S9MMK5|FPEB1_CAEEL FLYWCH-type zinc fin...,MMTTTVQKNCWRLDQTMLGLEKPGSSDISSSSTDTSAISPISVSSM...
3,sp|Q4VC44|FWCH1_HUMAN FLYWCH-type zinc finger-...,MPLPEPSEQEGESVKAGQEPSPKPGTDVIPAAPRKPREFSKLVLLT...
4,sp|Q86B87|MMD4_DROME Modifier of mdg4 OS=Droso...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
...,...,...
497978,Zpz_sc00227.1.g00450.1.am.mk Zoysia pacifica|b...,MYGSTVSKDLNLPAVQPQPATGARTPPPQMSSSGLLRYRSAPSNLL...
497979,Zpz_sc01778.1.g00020.1.am.mk Zoysia pacifica|M...,MARKPNQHAAAGTGAAAEEKKERRGLWSPEEDERLFTQITCHGVST...
497980,Zpz_sc01095.1.g00030.1.sm.mk Zoysia pacifica|H...,MEGSQSRSGGGSSSPPPFLIKTYEMVEDPATNRVVSWGPGGASFVV...
497981,Zpz_sc05215.1.g00010.1.am.mk Zoysia pacifica|b...,MSDDSDKQRQCRRGVGVHELDAAMALADLAGVSPEPQKLHLQPAAA...
497982,Zpz_sc00243.1.g00020.1.sm.mkhc Zoysia pacifica...,MDADFFADIDFAALLASFSDEPAAVSDLIVPSPPPSSPPPARDGES...

In [75]:
cl_seqs = protfasta.read_fasta("../output/cl_seqs.fasta", invalid_sequence_action='remove')
cl_seqs_df = pd.DataFrame({"id": cl_seqs.keys(), "seq": cl_seqs.values()})
sk_seqs = protfasta.read_fasta("../output/interpro_uniprot_evid_1_2.fasta", invalid_sequence_action='ignore')
sk_seqs_df = pd.DataFrame({"id": sk_seqs.keys(), "seq": sk_seqs.values()})
sk_seqs_df["id"] = sk_seqs_df["id"].str.split("|").str[1]
plant_seqs = protfasta.read_fasta("../data/PlantTFDB-all_TF_pep.fas", invalid_sequence_action='ignore')
plant_seqs_df = pd.DataFrame({"id": plant_seqs.keys(), "seq": plant_seqs.values()})
plant_seqs_df["id"] = plant_seqs_df["id"].str.split(" ").str[0]
all_seqs = pd.concat([plant_seqs_df, cl_seqs_df,sk_seqs_df])
all_seqs

                id                                                seq
0       KFK36254.1  MYSAIRSLPVDGSMGEYSDGTNLPIEACLVLTTDPKPRLRWTTELH...
1       KFK25038.1  MAPKHTDTIQNPPMPSSSSEEESASSGEDSDSSKKHNSASDSDPIK...
2       KFK35037.1  MTTTTTPHWPDFSSQKLPSIAATAAATAATAGQNQQNQNPSWMDEF...
3       KFK44643.1  MEGERHDSTTSSSRKRSHEPAEERPASHVATMAFKEKPYRGIRMRK...
4       KFK32619.1  MAKPPQFFHTLVNTHLVIPKDFFSKYIQGKSVDDTVELKSDSTDIN...
...            ...                                                ...
137431      W8C846  MNNITRLLANCTLNTTRCHLKYNAAALTAAIQLRGKCKVVVKPAPG...
137432      W8CA25  MAGRPRRQAATRTAQIIEISDSEDDNSVSKNKRRRRDSSFSPPPTK...
137433      W8QUS6  MSDSEKQPEEKEEPKKNVIATKVTGTVKWFNVKSGYGFINRDDTKE...
137434      X5CQH7  MSSARPLVLIASLLGASEALQSCHTRLVSSRVAATPRAAWALTMCD...
137435      X5DAG0  MRSRYGHVYEPEGGWASDSPEVDTGFSYADLEAGVGDIASFSRGDS...

[630660 rows x 2 columns]

In [76]:
final_clusters = pd.read_csv("/global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/consensus_AD_predictor/data/mmseqs/CL_SK_plant_seqs_disord_thresh_DB_clu_id75.tsv", sep = "\t", header = None)[[0]].drop_duplicates()
final_clusters = final_clusters.rename(columns = {0 : "id"})
final_clusters = pd.merge(final_clusters, all_seqs).drop_duplicates(subset = "id")
final_clusters

                    id                                                seq
0          Aco018208.1  MEELISTPSSCSPPASQQHFLGAGPGGRTPSSGAAPSEHHHHHAHP...
1          Aco023568.1  MEDEEDQPRSPSPYSSRSPSPSPSPSPPPITIVAPSSAAAAAAAAA...
2          Aco003398.1  MDLSGHEGEIPIPISSSYVGGGHGHGHSIIHESTPSLHHPSNGPPP...
3          Aco010666.1  MDSDVENRVVRFHECGEEEEEEEEEEGKRGEKDLDPRRAHYHPIPN...
4          Aco000547.1  MQETQKIVVSKPVASRPFSSSRYFSEVLPGSTSASPTTTLSDTAVA...
...                ...                                                ...
243147  XP_011099077.1  MLKVENSAGNDPGGARYNWLSSRRQPFWLCEACERAPAAFLCKADA...
243148  XP_011072165.1  MASSSSYNSPCAACKFLRRKCIPGCIFAPYFPPEEPQKFANVHKIF...
243149  XP_011084435.1  MPVAKLCTSGIVNAMKSEGGNDYLDTFIRQAIDLPGWPLMTPVKVQ...
243150  XP_011090405.1  MAGFFSLGGGGGRGRGISNSNPDQETTGHHNPSSEINPESWFLFRN...
243151  XP_011085124.1  MTAPPAADHHQSEENESKPNSTVDVEESGKKVVSSGSVRHYTRSKT...

[243151 rows x 2 columns]

In [77]:
train_seqs = final_clusters.rename(columns = {"seq" : "protein sequence"})
train_seqs["group"] = "test"
train_seqs

,id,protein sequence,group
0,Aco018208.1,MEELISTPSSCSPPASQQHFLGAGPGGRTPSSGAAPSEHHHHHAHP...,test
1,Aco023568.1,MEDEEDQPRSPSPYSSRSPSPSPSPSPPPITIVAPSSAAAAAAAAA...,test
2,Aco003398.1,MDLSGHEGEIPIPISSSYVGGGHGHGHSIIHESTPSLHHPSNGPPP...,test
3,Aco010666.1,MDSDVENRVVRFHECGEEEEEEEEEEGKRGEKDLDPRRAHYHPIPN...,test
4,Aco000547.1,MQETQKIVVSKPVASRPFSSSRYFSEVLPGSTSASPTTTLSDTAVA...,test
...,...,...,...
243147,XP_011099077.1,MLKVENSAGNDPGGARYNWLSSRRQPFWLCEACERAPAAFLCKADA...,test
243148,XP_011072165.1,MASSSSYNSPCAACKFLRRKCIPGCIFAPYFPPEEPQKFANVHKIF...,test
243149,XP_011084435.1,MPVAKLCTSGIVNAMKSEGGNDYLDTFIRQAIDLPGWPLMTPVKVQ...,test
243150,XP_011090405.1,MAGFFSLGGGGGRGRGISNSNPDQETTGHHNPSSEINPESWFLFRN...,test
243151,XP_011085124.1,MTAPPAADHHQSEENESKPNSTVDVEESGKKVVSSGSVRHYTRSKT...,test

In [78]:
train_seqs["group"] = "train"
train_seqs

,id,protein sequence,group
0,Aco018208.1,MEELISTPSSCSPPASQQHFLGAGPGGRTPSSGAAPSEHHHHHAHP...,train
1,Aco023568.1,MEDEEDQPRSPSPYSSRSPSPSPSPSPPPITIVAPSSAAAAAAAAA...,train
2,Aco003398.1,MDLSGHEGEIPIPISSSYVGGGHGHGHSIIHESTPSLHHPSNGPPP...,train
3,Aco010666.1,MDSDVENRVVRFHECGEEEEEEEEEEGKRGEKDLDPRRAHYHPIPN...,train
4,Aco000547.1,MQETQKIVVSKPVASRPFSSSRYFSEVLPGSTSASPTTTLSDTAVA...,train
...,...,...,...
243147,XP_011099077.1,MLKVENSAGNDPGGARYNWLSSRRQPFWLCEACERAPAAFLCKADA...,train
243148,XP_011072165.1,MASSSSYNSPCAACKFLRRKCIPGCIFAPYFPPEEPQKFANVHKIF...,train
243149,XP_011084435.1,MPVAKLCTSGIVNAMKSEGGNDYLDTFIRQAIDLPGWPLMTPVKVQ...,train
243150,XP_011090405.1,MAGFFSLGGGGGRGRGISNSNPDQETTGHHNPSSEINPESWFLFRN...,train
243151,XP_011085124.1,MTAPPAADHHQSEENESKPNSTVDVEESGKKVVSSGSVRHYTRSKT...,train

In [94]:
train_test_legend = pd.concat([test_seqs, train_seqs[["id", "protein sequence", "group"]]])
train_test_legend

,protein sequence,id,group
0,VVSTIPSVQLTAFSPAKKKLRLSPHLDFPIDSTFHPLSSN,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
1,TAFSPAKKKLRLSPHLDFPIDSTFHPLSSNIDPTFASLSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
2,RLSPHLDFPIDSTFHPLSSNIDPTFASLSSNLNPTPLTSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
3,DSTFHPLSSNIDPTFASLSSNLNPTPLTSSMPRPTNPFQG,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
4,IDPTFASLSSNLNPTPLTSSMPRPTNPFQGLPDYHVPAGI,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test
...,...,...,...
243147,MLKVENSAGNDPGGARYNWLSSRRQPFWLCEACERAPAAFLCKADA...,XP_011099077.1,train
243148,MASSSSYNSPCAACKFLRRKCIPGCIFAPYFPPEEPQKFANVHKIF...,XP_011072165.1,train
243149,MPVAKLCTSGIVNAMKSEGGNDYLDTFIRQAIDLPGWPLMTPVKVQ...,XP_011084435.1,train
243150,MAGFFSLGGGGGRGRGISNSNPDQETTGHHNPSSEINPESWFLFRN...,XP_011090405.1,train
243151,MTAPPAADHHQSEENESKPNSTVDVEESGKKVVSSGSVRHYTRSKT...,XP_011085124.1,train

In [95]:
# Give each a a numerical key for easier mapping back
train_test_legend["num_key"] = np.arange(len(train_test_legend))
train_test_legend

,protein sequence,id,group,num_key
0,VVSTIPSVQLTAFSPAKKKLRLSPHLDFPIDSTFHPLSSN,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,0
1,TAFSPAKKKLRLSPHLDFPIDSTFHPLSSNIDPTFASLSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,1
2,RLSPHLDFPIDSTFHPLSSNIDPTFASLSSNLNPTPLTSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,2
3,DSTFHPLSSNIDPTFASLSSNLNPTPLTSSMPRPTNPFQG,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,3
4,IDPTFASLSSNLNPTPLTSSMPRPTNPFQGLPDYHVPAGI,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,4
...,...,...,...,...
243147,MLKVENSAGNDPGGARYNWLSSRRQPFWLCEACERAPAAFLCKADA...,XP_011099077.1,train,261300
243148,MASSSSYNSPCAACKFLRRKCIPGCIFAPYFPPEEPQKFANVHKIF...,XP_011072165.1,train,261301
243149,MPVAKLCTSGIVNAMKSEGGNDYLDTFIRQAIDLPGWPLMTPVKVQ...,XP_011084435.1,train,261302
243150,MAGFFSLGGGGGRGRGISNSNPDQETTGHHNPSSEINPESWFLFRN...,XP_011090405.1,train,261303
243151,MTAPPAADHHQSEENESKPNSTVDVEESGKKVVSSGSVRHYTRSKT...,XP_011085124.1,train,261304

In [102]:
# 0 - 18153 = test
# 18154 + = train
train_test_legend[train_test_legend["group"] == "test"]

,protein sequence,id,group,num_key
0,VVSTIPSVQLTAFSPAKKKLRLSPHLDFPIDSTFHPLSSN,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,0
1,TAFSPAKKKLRLSPHLDFPIDSTFHPLSSNIDPTFASLSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,1
2,RLSPHLDFPIDSTFHPLSSNIDPTFASLSSNLNPTPLTSS,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,2
3,DSTFHPLSSNIDPTFASLSSNLNPTPLTSSMPRPTNPFQG,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,3
4,IDPTFASLSSNLNPTPLTSSMPRPTNPFQGLPDYHVPAGI,arf_evm_27.TU.AmTr_v1.0_scaffold00148.24|evm_2...,test,4
...,...,...,...,...
2066,LLGAPWGCGADIWSTACLIFELITGDFLFEPDEGHSYTKDDDHIAQ...,sanborn_D_nuc-nonhits_Q03656_575,test,18149
2067,QVLRLFIWIESKVDTLPVESLVSIFENSQFSGSEEIDSVDNIKIDT...,sanborn_D_nuc-nonhits_P17883_860,test,18150
2068,QRDPVYLGHLLYELTMHMEDFYALLIKLENDDDDDHDTASKALPSV...,sanborn_D_nuc-nonhits_P53036_375,test,18151
2069,EYCIGTTLNHPNIIETIEIVYENDRILQVMEYCEYDLFAIVMSNKM...,sanborn_D_nuc-nonhits_P22211_487,test,18152
2070,CLQDPVHEVRQSCFALLGDIVYFFNSELVIGNLEDFLKLIGTEIMH...,sanborn_D_nuc-nonhits_P38217_700,test,18153

In [96]:
train_test_legend["group"].value_counts()

group
train    243151
test      18154
Name: count, dtype: int64

In [97]:
protfasta.write_fasta(dict(zip(train_test_legend["num_key"], train_test_legend["protein sequence"])), "../output/train_test_to_cluster.fasta")

In [98]:
# From input data clusters with min identity .ipynb

def db_name(prefix, min_seq_id=0.5, fasta_path=False):
    if fasta_path:
        print(f"mmseqs createdb {fasta_path} {prefix}_DB") # - this alr exists
    id_thresh = int(min_seq_id * 100)
    print(f"mmseqs cluster {prefix}_DB {prefix}_DB_clu_id{id_thresh} {prefix}tmp_id{id_thresh} --min-seq-id {min_seq_id}")                      
    print(f"mmseqs createtsv {prefix}_DB {prefix}_DB {prefix}_DB_clu_id{id_thresh} {prefix}_DB_clu_id{id_thresh}.tsv")

In [99]:
db_name("test_train", 0.75, "../../output/train_test_to_cluster.fasta")

mmseqs createdb ../../output/train_test_to_cluster.fasta test_train_DB
mmseqs cluster test_train_DB test_train_DB_clu_id75 test_traintmp_id75 --min-seq-id 0.75
mmseqs createtsv test_train_DB test_train_DB test_train_DB_clu_id75 test_train_DB_clu_id75.tsv

In [100]:
test_train_clusters = pd.read_csv("../data/mmseqs/test_train_DB_clu_id75.tsv", sep = "\t", header = None)
test_train_clusters

             0       1
0       143781  143781
1       143813  143813
2       143845  143845
3       143877  143877
4       143909  143909
...        ...     ...
261300  228395  228395
261301  228427  228427
261302  228459  228459
261303  228491  228491
261304  228523  228523

[261305 rows x 2 columns]

In [101]:
# 10,000 seqs removed
test_train_clusters[0].value_counts()

0
14086    447
15928    198
13175    178
13537    162
13702    137
        ...
48286      1
48318      1
48350      1
48382      1
47902      1
Name: count, Length: 253032, dtype: int64

In [105]:
# 0 - 18153 = test
# 18154 + = train

test_train_clusters["cluster_leader_group"] = np.where(test_train_clusters[0] <= 18153, 'test', 'train')
test_train_clusters["cluster_member_group"] = np.where(test_train_clusters[1] <= 18153, 'test', 'train')
test_train_clusters

             0       1 cluster_leader_group cluster_member_group
0       143781  143781                train                train
1       143813  143813                train                train
2       143845  143845                train                train
3       143877  143877                train                train
4       143909  143909                train                train
...        ...     ...                  ...                  ...
261300  228395  228395                train                train
261301  228427  228427                train                train
261302  228459  228459                train                train
261303  228491  228491                train                train
261304  228523  228523                train                train

[261305 rows x 4 columns]

In [108]:
temp = test_train_clusters[test_train_clusters["cluster_leader_group"] == "test"]
temp[0].value_counts()

0
14086    447
15928    198
13175    178
13537    162
13702    137
        ...
12179      1
12211      1
12243      1
12275      1
11987      1
Name: count, Length: 10513, dtype: int64

In [106]:
test_train_clusters[test_train_clusters["cluster_leader_group"] != test_train_clusters["cluster_member_group"]]

Empty DataFrame
Columns: [0, 1, cluster_leader_group, cluster_member_group]
Index: []

In [113]:
# There are no clusters where train member is clustered with a test sequence!