In [1]:
import pandas as pd
import protfasta
import glob

# Gathering all inputs

## 1. SK Interpro evidence 1 and 2 sequences

In [2]:
def return_df(fasta_path):
    fasta_dict = protfasta.read_fasta(fasta_path, invalid_sequence_action='ignore')
    return pd.DataFrame({'id' : fasta_dict.keys(), 'seq' : fasta_dict.values()})

In [3]:
sk_seqs = return_df("../output/interpro_uniprot_evid_1_2.fasta")
sk_seqs

,id,seq
0,tr|A0A0B4K6B8|A0A0B4K6B8_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
1,tr|A0A0B4K7A6|A0A0B4K7A6_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
2,sp|A0A5S9MMK5|FPEB1_CAEEL FLYWCH-type zinc fin...,MMTTTVQKNCWRLDQTMLGLEKPGSSDISSSSTDTSAISPISVSSM...
3,sp|Q4VC44|FWCH1_HUMAN FLYWCH-type zinc finger-...,MPLPEPSEQEGESVKAGQEPSPKPGTDVIPAAPRKPREFSKLVLLT...
4,sp|Q86B87|MMD4_DROME Modifier of mdg4 OS=Droso...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
...,...,...
137431,tr|W8C846|W8C846_CERCA (Mediterranean fruit fl...,MNNITRLLANCTLNTTRCHLKYNAAALTAAIQLRGKCKVVVKPAPG...
137432,tr|W8CA25|W8CA25_CERCA (Mediterranean fruit fl...,MAGRPRRQAATRTAQIIEISDSEDDNSVSKNKRRRRDSSFSPPPTK...
137433,tr|W8QUS6|W8QUS6_MIMNO Cold shock domain prote...,MSDSEKQPEEKEEPKKNVIATKVTGTVKWFNVKSGYGFINRDDTKE...
137434,tr|X5CQH7|X5CQH7_9EUKA 30S plastidal ribosomal...,MSSARPLVLIASLLGASEALQSCHTRLVSSRVAATPRAAWALTMCD...
137435,tr|X5DAG0|X5DAG0_9EUKA 30S plastidal ribosomal...,MRSRYGHVYEPEGGWASDSPEVDTGFSYADLEAGVGDIASFSRGDS...

## 2. CL yeast orthologs

In [4]:
cl_paths = glob.glob("/global/scratch/projects/fc_mvslab/OpenProjects/Claire/fasta_files/*")
cl_seqs = []
for cl_path in cl_paths:
    cl_seqs.append(return_df(cl_path))
cl_seqs = pd.concat(cl_seqs)
cl_seqs = cl_seqs.reset_index(drop = True)
cl_seqs

,id,seq
0,g003334.m1_alloascoidea_hylecoeti.final,MEQQPTQDNISNETHGSEEPPTKKSRSDNGTECETTDATPTINRNE...
1,g002909.m1_arxula_adeninivorans.final,MAEPDQISEGHESPGSSNKRQLHEVDHSDRSPRPEDTNGTKRPRTD...
2,g001599.m1_ashbya_aceri.final,MALGIPYLHEYDEDTLKQRLEAVLPGLPYATQLTLKSLPLLNDIST...
3,g002398.m1_brettanomyces_anomalus.final,MADPDTSHKSPLLSENNLPHNNKKISDNVPTEEDGKKEAQTETPQI...
4,C2_04200W_A_candida_albicans.cgd,MSDQLEKDIEESIANLDYQQNQEHHETEQDKDKEHQDVEKQSSEEE...
...,...,...
112621,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112622,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112623,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112624,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...
112625,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...

In [5]:
import numpy as np
np.percentile(cl_seqs["seq"].str.len(), 99)

1384.0

In [6]:
cl_seqs = cl_seqs.drop_duplicates(subset = "seq")
cl_seqs

,id,seq
0,g003334.m1_alloascoidea_hylecoeti.final,MEQQPTQDNISNETHGSEEPPTKKSRSDNGTECETTDATPTINRNE...
1,g002909.m1_arxula_adeninivorans.final,MAEPDQISEGHESPGSSNKRQLHEVDHSDRSPRPEDTNGTKRPRTD...
2,g001599.m1_ashbya_aceri.final,MALGIPYLHEYDEDTLKQRLEAVLPGLPYATQLTLKSLPLLNDIST...
3,g002398.m1_brettanomyces_anomalus.final,MADPDTSHKSPLLSENNLPHNNKKISDNVPTEEDGKKEAQTETPQI...
4,C2_04200W_A_candida_albicans.cgd,MSDQLEKDIEESIANLDYQQNQEHHETEQDKDKEHQDVEKQSSEEE...
...,...,...
112621,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112622,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112623,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112624,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...
112625,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...

In [7]:
cl_seqs[(cl_seqs["seq"].str.len()<53)]

,id,seq
2092,g003772.m1_yHMPu5000034996_candida_sojae_SPADE...,SVSDAQQQQQLLFDDNIDFLGGPPVLMTADLFNEDWEALFPDYVFNSKN
11754,g001433.m1_yHMPu5000035005_lodderomyces_elongi...,LQQQPMDIPMAGSFVSQIDSFFQQQSNGWMDNQDDDFLGWFDLNMLPDQ
24716,g006857.m1_yHMPu5000034631_martiniozyma_abieso...,ILSTDFLNDTDEYGLPWDFIETAFESGEDRLLLESLGLVLGDDDIY...
41767,g001649.m1_yHMPu5000035711_botryozyma_cognata_...,MSYSSKGEYSNNNTNVNGFTQFYNPNSTFSSYNDSTEAYPDSLSRSMRP
51810,g006027.m1_yHMPu5000041803_Metschnikowia_zizyp...,RANGGPGNGKLKTFSRNDALSRHIKVKHGLAGQEALDLINAAKENV...
67522,g011087.m1_yHMPu5000035263_Candida_solani_SPAD...,SSFLRIWVSENAQNYQILNAKKPDAYKFKLIQFFININLSINYGLV...
70245,g001009.m1_yHMPu5000040795_metschnikowia_matae...,PILEDLNDYMNLYEKEFNECLLPVHSYANSQTLRNPMIDNFENIPSFH
79951,g000403.m1_yHMPu5000038315_wickerhamomyces_tra...,MPPKIISKEPSYVTPLHQIQHKPPPKRIRVSRACDTCRKRKVRCDGKMP
84881,g000265.m1_yHMPu5000034950_citeromyces_hawaiie...,PDWESYDFTKLDPSSPEDKEFVNDMWAWDKPVIVNGESREIADGKVLK
84903,g003901.m1_yHMPu5000034958_hanseniaspora_opunt...,PDWESYAYTKLDASKEEDKKFIENMWAWDEPVVVDGVSKEIADGKVLK
85503,g001781.m1_yHMPu5000037218_Ogataea_degrootiae_...,PDYESYEFTKLDASLPETKAFVNNMWAWDEPVEINGEKKEIVDGKVFK
85505,g004499.m1_yHMPu5000037218_Ogataea_degrootiae_...,MRADQLLDLDVSIEEDRTTDSFKKTFPLGKAPGFVGAKGYKLTESI...
85561,g003517.m1_yHMPu5000037240_candida_sp_210210.f...,MSQGTLYVMEISPRSFILEDIVKHYKLDVKVTAEKDAAFNAKFPLA...
89796,g000779.m1_yHMPu5000038063_candida_xylanilytic...,MNFEPTDYIQHLNLDLDSVVSPTMTQQQLDHELDLFSQANDFFSLDVLG
97559,g004101.m1_yHMPu5000034955_hanseniaspora_valby...,MSRNISTNTEFSKPDVIVANHLSPVTPTTTTTNNNTAMDQPIQPSV...
98181,g004371.m1_yHMPu5000035273_wickerhamomyces_ano...,MSSLGRGTHVDEDSSAEALWRMYAKAKASLPYKERMQNLTWRMMSI...
107122,g000758.m1_yHMPu5000035663_Meyerozyma_guillier...,MSAANPMILTGDSFESADVFNSASATSDRTLGSQMLAMKASENSEE...
109301,g000838.m1_yHMPu5000037895_candida_jaroonii_18...,MDEYDNSEVNNEEEYDRLLLLSLILQINLDSCFSVYENFDLIFAIGDHM
110329,g002579.m1_yHMPu5000034684_blastobotrys_attino...,RAKATANPTPEMVKGMAQLEQKLRLMRQKRVASSAELGSDNDRGSK...

In [8]:
cl_seqs[(cl_seqs["seq"].str.len() > 1891)]

,id,seq
1166,g006333.m1_yHMPu5000041796_saccharomycopsis_fi...,MSYHRDSNSNKNETIDNDNDNDNQRDNLIPVQQHGHDQGQHTLEEL...
2412,g000315.m1_yHMPu5000035696_hanseniaspora_singu...,MPQPTLNNTALVIQETGYSYEKHVDDFRNIMTKLLYECSNIFKQHL...
4974,g004370.m1_hanseniaspora_gamundiae.final,MSQSMTPSVSTPATSTAATFSKLQSCDRCRLKKIKCSFSSDKALNG...
5673,g002830.m1_yHMPu5000035684_kloeckera_hatyaiens...,MANSDKAKKEQQYQSCDRCRSKKIKCTYDKKSLKQCINCKNAFLEC...
9802,g002499.m1_yHMPu5000034628_pichia_fermentans_1...,MDFQITREAPTRGLCRAQLTKEGRILFQTRNGLMMYDTNTGFRGKT...
...,...,...
111010,g000871.m1_yHMPu5000038316_wickerhamomyces_cha...,MSSSTTGDIDPFHAINGEPSTGIEANSLQLHHEPALDNASAQSPNL...
111214,g001043.m1_yHMPu5000041818_magnusiomyces_tetra...,MSTVSPGKEAVAEAVTKASIADNGATETGAAARVNDTNNTNNTSNS...
111215,g004106.m1_yHMPu5000041818_magnusiomyces_tetra...,MSTVSPGTQPVPSSHDSALNSNERDAQAPYTQASEPADNQHKSDDN...
111397,g004022.m1_yHDO590_kloeckera_taiwanica_180604....,MIVYANKVRVLFGLVVLVSIAAAQAEGLHLLQRDSAQDEVLGTGLY...
111630,g002592.m1_yHMPu5000034708_kazachstania_yasuni...,MMLSKYHIFILVWLNVVVQTAWGQPFNIDFWNHLMKRDLSPSNNNT...

In [9]:
protfasta.write_fasta(dict(zip(cl_seqs["id"], cl_seqs["seq"])), "../output/cl_seqs.fasta")

##  Both together now

In [12]:
all_seqs = pd.concat([sk_seqs, cl_seqs])
all_seqs

,id,seq
0,tr|A0A0B4K6B8|A0A0B4K6B8_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
1,tr|A0A0B4K7A6|A0A0B4K7A6_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
2,sp|A0A5S9MMK5|FPEB1_CAEEL FLYWCH-type zinc fin...,MMTTTVQKNCWRLDQTMLGLEKPGSSDISSSSTDTSAISPISVSSM...
3,sp|Q4VC44|FWCH1_HUMAN FLYWCH-type zinc finger-...,MPLPEPSEQEGESVKAGQEPSPKPGTDVIPAAPRKPREFSKLVLLT...
4,sp|Q86B87|MMD4_DROME Modifier of mdg4 OS=Droso...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
...,...,...
112621,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112622,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112623,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112624,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...
112625,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...

In [13]:
# Dropping duplicate sequences
all_seqs = all_seqs.drop_duplicates(subset = "seq")
all_seqs

,id,seq
0,tr|A0A0B4K6B8|A0A0B4K6B8_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
1,tr|A0A0B4K7A6|A0A0B4K7A6_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
2,sp|A0A5S9MMK5|FPEB1_CAEEL FLYWCH-type zinc fin...,MMTTTVQKNCWRLDQTMLGLEKPGSSDISSSSTDTSAISPISVSSM...
3,sp|Q4VC44|FWCH1_HUMAN FLYWCH-type zinc finger-...,MPLPEPSEQEGESVKAGQEPSPKPGTDVIPAAPRKPREFSKLVLLT...
4,sp|Q86B87|MMD4_DROME Modifier of mdg4 OS=Droso...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
...,...,...
112621,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112622,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112623,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112624,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...
112625,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...

In [18]:
np.percentile(all_seqs["seq"].str.len(), 99)

1731.1399999999849

In [16]:
max(cl_seqs["seq"].str.len())

3146

In [19]:
all_seqs[all_seqs["seq"].str.len() < np.percentile(all_seqs["seq"].str.len(), 99)]

,id,seq
0,tr|A0A0B4K6B8|A0A0B4K6B8_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
1,tr|A0A0B4K7A6|A0A0B4K7A6_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
2,sp|A0A5S9MMK5|FPEB1_CAEEL FLYWCH-type zinc fin...,MMTTTVQKNCWRLDQTMLGLEKPGSSDISSSSTDTSAISPISVSSM...
3,sp|Q4VC44|FWCH1_HUMAN FLYWCH-type zinc finger-...,MPLPEPSEQEGESVKAGQEPSPKPGTDVIPAAPRKPREFSKLVLLT...
4,sp|Q86B87|MMD4_DROME Modifier of mdg4 OS=Droso...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...
...,...,...
112621,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112622,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112623,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
112624,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...
112625,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...

# Running mmseqs2

## 1. SK seqs alone

In [37]:
clusters = pd.read_csv("../output/mmseqs/IP_DB_clu.tsv", sep = "\t", header = None)
clusters = clusters.rename(columns = {0: "cluster_centroid", 1: "uniprotID"})
clusters

       cluster_centroid   uniprotID
0            A0A0P0WV74  A0A0P0WV74
1                P31503      P31503
2                P31503      P16143
3                P31503      E9Q6Z8
4                P31503  A0A0A0MQM6
...                 ...         ...
137431           G5B7M9  A0AAX6S0N3
137432           G5B7M9  A0AAX6S1G0
137433           G5B7M9      F7H422
137434           G5B7M9  A0A2K5CJ38
137435           G5B7M9  A0AAX6S2T2

[137436 rows x 2 columns]

# 2. CL seqs alone

# hide

In [8]:
seqs = protfasta.read_fasta("../output/interpro_uniprot_evid_1_2.fasta")
seqs = pd.DataFrame({"id" : seqs.keys(), "seq" : seqs.values()})
seqs["uniprotID"] = seqs["id"].str.split("|").str[1]
seqs = pd.merge(seqs, clusters, on = "uniprotID")
seqs

,id,seq,uniprotID,cluster_centroid
0,tr|A0A0B4K6B8|A0A0B4K6B8_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...,A0A0B4K6B8,A0A023ESS1
1,tr|A0A0B4K7A6|A0A0B4K7A6_DROME Modifier of mdg...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...,A0A0B4K7A6,A0A023ESS1
2,sp|A0A5S9MMK5|FPEB1_CAEEL FLYWCH-type zinc fin...,MMTTTVQKNCWRLDQTMLGLEKPGSSDISSSSTDTSAISPISVSSM...,A0A5S9MMK5,A8XJ98
3,sp|Q4VC44|FWCH1_HUMAN FLYWCH-type zinc finger-...,MPLPEPSEQEGESVKAGQEPSPKPGTDVIPAAPRKPREFSKLVLLT...,Q4VC44,Q4VC44
4,sp|Q86B87|MMD4_DROME Modifier of mdg4 OS=Droso...,MADDEQFSLCWNNFNTNLSAGFHESLCRGDLVDVSLAAEGQIVKAH...,Q86B87,A0A023ESS1
...,...,...,...,...
137431,tr|W8C846|W8C846_CERCA (Mediterranean fruit fl...,MNNITRLLANCTLNTTRCHLKYNAAALTAAIQLRGKCKVVVKPAPG...,W8C846,A0A0P4VQK3
137432,tr|W8CA25|W8CA25_CERCA (Mediterranean fruit fl...,MAGRPRRQAATRTAQIIEISDSEDDNSVSKNKRRRRDSSFSPPPTK...,W8CA25,Q9N4L5
137433,tr|W8QUS6|W8QUS6_MIMNO Cold shock domain prote...,MSDSEKQPEEKEEPKKNVIATKVTGTVKWFNVKSGYGFINRDDTKE...,W8QUS6,W8QUS6
137434,tr|X5CQH7|X5CQH7_9EUKA 30S plastidal ribosomal...,MSSARPLVLIASLLGASEALQSCHTRLVSSRVAATPRAAWALTMCD...,X5CQH7,X5CQH7
137435,tr|X5DAG0|X5DAG0_9EUKA 30S plastidal ribosomal...,MRSRYGHVYEPEGGWASDSPEVDTGFSYADLEAGVGDIASFSRGDS...,X5DAG0,P46228

In [ ]:
cluster_counts = seqs["cluster_centroid"].value_counts()
cluster_counts

In [ ]:
import seaborn as sns
sns.lineplot(seqs["cluster_centroid"].value_counts())

/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/seaborn/_oldcore.py:1119: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  with pd.option_context('mode.use_inf_as_na', True):
/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/seaborn/_oldcore.py:1119: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  with pd.option_context('mode.use_inf_as_na', True):

KeyboardInterrupt

Error in callback <function _draw_all_if_interactive at 0x14f25c64f100> (for post_execute), with arguments args (),kwargs {}:

KeyboardInterrupt: