In [1]:
import pandas as pd
import glob 
import numpy as np
import protfasta
from ete4 import Tree
from ete4.treeview import TreeStyle, TextFace, NodeStyle

In [83]:
def return_df(fasta_path):
    fasta_dict = protfasta.read_fasta(fasta_path, invalid_sequence_action='ignore')
    return pd.DataFrame({'id' : fasta_dict.keys(), 'seq' : fasta_dict.values()})
    
cl_seqs = return_df("../output/cl_seqs.fasta")
cl_seqs

,id,seq
0,g003334.m1_alloascoidea_hylecoeti.final,MEQQPTQDNISNETHGSEEPPTKKSRSDNGTECETTDATPTINRNE...
1,g002909.m1_arxula_adeninivorans.final,MAEPDQISEGHESPGSSNKRQLHEVDHSDRSPRPEDTNGTKRPRTD...
2,g001599.m1_ashbya_aceri.final,MALGIPYLHEYDEDTLKQRLEAVLPGLPYATQLTLKSLPLLNDIST...
3,g002398.m1_brettanomyces_anomalus.final,MADPDTSHKSPLLSENNLPHNNKKISDNVPTEEDGKKEAQTETPQI...
4,C2_04200W_A_candida_albicans.cgd,MSDQLEKDIEESIANLDYQQNQEHHETEQDKDKEHQDVEKQSSEEE...
...,...,...
110807,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
110808,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
110809,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...
110810,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...
110811,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...

In [139]:
cl_seqs["species1"] = cl_seqs["id"].str.extract(r"(.{3,}_.{3,})\..*$")
cl_seqs["species2"] = cl_seqs["species1"].str.extract(r"\d_(.*)")#.str[1:]#.str[-2] + " " + cl_seqs["species"].str.split("_").str[-1]
cl_seqs["species3"] = cl_seqs["species2"].str.replace(r"_._", "_", regex=True)
cl_seqs["species4"] = cl_seqs["species3"].str.extract("_(.*)")
cl_seqs["species5"] = cl_seqs["species4"].str.extract(r"(.*)_\d")
cl_seqs["species6"] = cl_seqs["species4"].str.split("_sp").str[0]
cl_seqs["species7"] = cl_seqs["species1"].str.split("_").str[1] + "_" + cl_seqs["species1"].str.split("_").str[2]
cl_seqs["species8"] = cl_seqs["species7"].str.split("_").str[1]

cl_seqs["species1_done"] = cl_seqs["species1"].str.count("_") == 1
cl_seqs["species2_done"] = cl_seqs["species2"].str.count("_") == 1
cl_seqs["species3_done"] = cl_seqs["species3"].str.count("_") == 1
cl_seqs["species4_done"] = cl_seqs["species4"].str.count("_") == 1
cl_seqs["species5_done"] = cl_seqs["species5"].str.count("_") == 1
cl_seqs["species6_done"] = cl_seqs["species6"].str.len() > 1
cl_seqs["species7_done"] = cl_seqs["species7"].str.count("_") == 1
    
cl_seqs["done"] = cl_seqs["species1_done"] | cl_seqs["species2_done"] | cl_seqs["species3_done"] | cl_seqs["species4_done"] | cl_seqs["species5_done"] | cl_seqs["species6_done"] | cl_seqs["species7_done"]
cl_seqs

,id,seq,species1,species2,species3,species4,species1_done,species2_done,species3_done,species4_done,...,species7_done,species1_filtered,species2_filtered,species3_filtered,species4_filtered,species5_filtered,species6_filtered,species7_filtered,final_species,species8
0,g003334.m1_alloascoidea_hylecoeti.final,MEQQPTQDNISNETHGSEEPPTKKSRSDNGTECETTDATPTINRNE...,g003334.m1_alloascoidea_hylecoeti,alloascoidea_hylecoeti,alloascoidea_hylecoeti,hylecoeti,False,True,True,False,...,True,None,alloascoidea_hylecoeti,alloascoidea_hylecoeti,None,None,None,alloascoidea_hylecoeti,alloascoidea_hylecoeti,hylecoeti
1,g002909.m1_arxula_adeninivorans.final,MAEPDQISEGHESPGSSNKRQLHEVDHSDRSPRPEDTNGTKRPRTD...,g002909.m1_arxula_adeninivorans,arxula_adeninivorans,arxula_adeninivorans,adeninivorans,False,True,True,False,...,True,None,arxula_adeninivorans,arxula_adeninivorans,None,None,None,arxula_adeninivorans,arxula_adeninivorans,adeninivorans
2,g001599.m1_ashbya_aceri.final,MALGIPYLHEYDEDTLKQRLEAVLPGLPYATQLTLKSLPLLNDIST...,g001599.m1_ashbya_aceri,ashbya_aceri,ashbya_aceri,aceri,False,True,True,False,...,True,None,ashbya_aceri,ashbya_aceri,None,None,None,ashbya_aceri,ashbya_aceri,aceri
3,g002398.m1_brettanomyces_anomalus.final,MADPDTSHKSPLLSENNLPHNNKKISDNVPTEEDGKKEAQTETPQI...,g002398.m1_brettanomyces_anomalus,brettanomyces_anomalus,brettanomyces_anomalus,anomalus,False,True,True,False,...,True,None,brettanomyces_anomalus,brettanomyces_anomalus,None,None,None,brettanomyces_anomalus,brettanomyces_anomalus,anomalus
4,C2_04200W_A_candida_albicans.cgd,MSDQLEKDIEESIANLDYQQNQEHHETEQDKDKEHQDVEKQSSEEE...,C2_04200W_A_candida_albicans,04200W_A_candida_albicans,04200W_candida_albicans,candida_albicans,False,False,False,True,...,True,None,None,None,candida_albicans,None,candida_albicans,None,candida_albicans,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110807,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005054.m1_saccharomyces_mikatae,saccharomyces_mikatae,saccharomyces_mikatae,mikatae,False,True,True,False,...,True,None,saccharomyces_mikatae,saccharomyces_mikatae,None,None,None,saccharomyces_mikatae,saccharomyces_mikatae,mikatae
110808,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005100.m1_saccharomyces_paradoxus,saccharomyces_paradoxus,saccharomyces_paradoxus,paradoxus,False,True,True,False,...,True,None,saccharomyces_paradoxus,saccharomyces_paradoxus,None,None,None,saccharomyces_paradoxus,saccharomyces_paradoxus,paradoxus
110809,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g002076.m1_saccharomyces_uvarum,saccharomyces_uvarum,saccharomyces_uvarum,uvarum,False,True,True,False,...,True,None,saccharomyces_uvarum,saccharomyces_uvarum,None,None,None,saccharomyces_uvarum,saccharomyces_uvarum,uvarum
110810,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...,g004724.m1_yHMPu5000034597_candida_stellimalic...,yHMPu5000034597_candida_stellimalicola_180604,yHMPu5000034597_candida_stellimalicola_180604,candida_stellimalicola_180604,False,False,False,False,...,True,None,None,None,None,candida_stellimalicola,None,None,candida_stellimalicola,candida
110811,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES,yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES,Schwanniomyces_sp_nov_plate33_SPADES,False,False,False,False,...,True,None,None,None,None,None,None,None,None,Schwanniomyces

In [140]:
for col in ["species1", "species2", "species3", "species4", "species5", "species6", "species7"]:
    cl_seqs[col + "_filtered"] = cl_seqs[col].apply(lambda x: x if pd.notnull(x) and x.count("_") == 1 and not any(char.isdigit() for char in x) else None)
cl_seqs

,id,seq,species1,species2,species3,species4,species1_done,species2_done,species3_done,species4_done,...,species7_done,species1_filtered,species2_filtered,species3_filtered,species4_filtered,species5_filtered,species6_filtered,species7_filtered,final_species,species8
0,g003334.m1_alloascoidea_hylecoeti.final,MEQQPTQDNISNETHGSEEPPTKKSRSDNGTECETTDATPTINRNE...,g003334.m1_alloascoidea_hylecoeti,alloascoidea_hylecoeti,alloascoidea_hylecoeti,hylecoeti,False,True,True,False,...,True,None,alloascoidea_hylecoeti,alloascoidea_hylecoeti,None,None,None,alloascoidea_hylecoeti,alloascoidea_hylecoeti,hylecoeti
1,g002909.m1_arxula_adeninivorans.final,MAEPDQISEGHESPGSSNKRQLHEVDHSDRSPRPEDTNGTKRPRTD...,g002909.m1_arxula_adeninivorans,arxula_adeninivorans,arxula_adeninivorans,adeninivorans,False,True,True,False,...,True,None,arxula_adeninivorans,arxula_adeninivorans,None,None,None,arxula_adeninivorans,arxula_adeninivorans,adeninivorans
2,g001599.m1_ashbya_aceri.final,MALGIPYLHEYDEDTLKQRLEAVLPGLPYATQLTLKSLPLLNDIST...,g001599.m1_ashbya_aceri,ashbya_aceri,ashbya_aceri,aceri,False,True,True,False,...,True,None,ashbya_aceri,ashbya_aceri,None,None,None,ashbya_aceri,ashbya_aceri,aceri
3,g002398.m1_brettanomyces_anomalus.final,MADPDTSHKSPLLSENNLPHNNKKISDNVPTEEDGKKEAQTETPQI...,g002398.m1_brettanomyces_anomalus,brettanomyces_anomalus,brettanomyces_anomalus,anomalus,False,True,True,False,...,True,None,brettanomyces_anomalus,brettanomyces_anomalus,None,None,None,brettanomyces_anomalus,brettanomyces_anomalus,anomalus
4,C2_04200W_A_candida_albicans.cgd,MSDQLEKDIEESIANLDYQQNQEHHETEQDKDKEHQDVEKQSSEEE...,C2_04200W_A_candida_albicans,04200W_A_candida_albicans,04200W_candida_albicans,candida_albicans,False,False,False,True,...,True,None,None,None,candida_albicans,None,candida_albicans,None,candida_albicans,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110807,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005054.m1_saccharomyces_mikatae,saccharomyces_mikatae,saccharomyces_mikatae,mikatae,False,True,True,False,...,True,None,saccharomyces_mikatae,saccharomyces_mikatae,None,None,None,saccharomyces_mikatae,saccharomyces_mikatae,mikatae
110808,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005100.m1_saccharomyces_paradoxus,saccharomyces_paradoxus,saccharomyces_paradoxus,paradoxus,False,True,True,False,...,True,None,saccharomyces_paradoxus,saccharomyces_paradoxus,None,None,None,saccharomyces_paradoxus,saccharomyces_paradoxus,paradoxus
110809,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g002076.m1_saccharomyces_uvarum,saccharomyces_uvarum,saccharomyces_uvarum,uvarum,False,True,True,False,...,True,None,saccharomyces_uvarum,saccharomyces_uvarum,None,None,None,saccharomyces_uvarum,saccharomyces_uvarum,uvarum
110810,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...,g004724.m1_yHMPu5000034597_candida_stellimalic...,yHMPu5000034597_candida_stellimalicola_180604,yHMPu5000034597_candida_stellimalicola_180604,candida_stellimalicola_180604,False,False,False,False,...,True,None,None,None,None,candida_stellimalicola,None,None,candida_stellimalicola,candida
110811,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES,yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES,Schwanniomyces_sp_nov_plate33_SPADES,False,False,False,False,...,True,None,None,None,None,None,None,None,None,Schwanniomyces

In [141]:
cl_seqs["final_species"] = pd.Series([None] * len(cl_seqs), index=cl_seqs.index)
cl_seqs["final_species"] = cl_seqs["species1_filtered"].fillna(cl_seqs["species2_filtered"]).fillna(cl_seqs["species3_filtered"]).fillna(cl_seqs["species4_filtered"]).fillna(cl_seqs["species5_filtered"]).fillna(cl_seqs["species6_filtered"]).fillna(cl_seqs["species7_filtered"])
cl_seqs["final_species"] = cl_seqs["final_species"].str.split(r'\d+_').str[-1]
cl_seqs

,id,seq,species1,species2,species3,species4,species1_done,species2_done,species3_done,species4_done,...,species7_done,species1_filtered,species2_filtered,species3_filtered,species4_filtered,species5_filtered,species6_filtered,species7_filtered,final_species,species8
0,g003334.m1_alloascoidea_hylecoeti.final,MEQQPTQDNISNETHGSEEPPTKKSRSDNGTECETTDATPTINRNE...,g003334.m1_alloascoidea_hylecoeti,alloascoidea_hylecoeti,alloascoidea_hylecoeti,hylecoeti,False,True,True,False,...,True,None,alloascoidea_hylecoeti,alloascoidea_hylecoeti,None,None,None,alloascoidea_hylecoeti,alloascoidea_hylecoeti,hylecoeti
1,g002909.m1_arxula_adeninivorans.final,MAEPDQISEGHESPGSSNKRQLHEVDHSDRSPRPEDTNGTKRPRTD...,g002909.m1_arxula_adeninivorans,arxula_adeninivorans,arxula_adeninivorans,adeninivorans,False,True,True,False,...,True,None,arxula_adeninivorans,arxula_adeninivorans,None,None,None,arxula_adeninivorans,arxula_adeninivorans,adeninivorans
2,g001599.m1_ashbya_aceri.final,MALGIPYLHEYDEDTLKQRLEAVLPGLPYATQLTLKSLPLLNDIST...,g001599.m1_ashbya_aceri,ashbya_aceri,ashbya_aceri,aceri,False,True,True,False,...,True,None,ashbya_aceri,ashbya_aceri,None,None,None,ashbya_aceri,ashbya_aceri,aceri
3,g002398.m1_brettanomyces_anomalus.final,MADPDTSHKSPLLSENNLPHNNKKISDNVPTEEDGKKEAQTETPQI...,g002398.m1_brettanomyces_anomalus,brettanomyces_anomalus,brettanomyces_anomalus,anomalus,False,True,True,False,...,True,None,brettanomyces_anomalus,brettanomyces_anomalus,None,None,None,brettanomyces_anomalus,brettanomyces_anomalus,anomalus
4,C2_04200W_A_candida_albicans.cgd,MSDQLEKDIEESIANLDYQQNQEHHETEQDKDKEHQDVEKQSSEEE...,C2_04200W_A_candida_albicans,04200W_A_candida_albicans,04200W_candida_albicans,candida_albicans,False,False,False,True,...,True,None,None,None,candida_albicans,None,candida_albicans,None,candida_albicans,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110807,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005054.m1_saccharomyces_mikatae,saccharomyces_mikatae,saccharomyces_mikatae,mikatae,False,True,True,False,...,True,None,saccharomyces_mikatae,saccharomyces_mikatae,None,None,None,saccharomyces_mikatae,saccharomyces_mikatae,mikatae
110808,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005100.m1_saccharomyces_paradoxus,saccharomyces_paradoxus,saccharomyces_paradoxus,paradoxus,False,True,True,False,...,True,None,saccharomyces_paradoxus,saccharomyces_paradoxus,None,None,None,saccharomyces_paradoxus,saccharomyces_paradoxus,paradoxus
110809,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g002076.m1_saccharomyces_uvarum,saccharomyces_uvarum,saccharomyces_uvarum,uvarum,False,True,True,False,...,True,None,saccharomyces_uvarum,saccharomyces_uvarum,None,None,None,saccharomyces_uvarum,saccharomyces_uvarum,uvarum
110810,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...,g004724.m1_yHMPu5000034597_candida_stellimalic...,yHMPu5000034597_candida_stellimalicola_180604,yHMPu5000034597_candida_stellimalicola_180604,candida_stellimalicola_180604,False,False,False,False,...,True,None,None,None,None,candida_stellimalicola,None,None,candida_stellimalicola,candida
110811,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES,yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES,Schwanniomyces_sp_nov_plate33_SPADES,False,False,False,False,...,True,None,None,None,None,None,None,None,None,Schwanniomyces

In [147]:
cl_seqs[cl_seqs["final_species"].isna()]["species6"]

99        Kazachstania_barnettii_SPADES
103          Myxozyma_mucilagina_SPADES
119       Zygoascus_bituminiphia_SPADES
129                          Nakazawaea
134                          Yamadazyma
                      ...
110796                    Metschnikowia
110797                   Schwanniomyces
110798                   Schwanniomyces
110799                   Schwanniomyces
110811                   Schwanniomyces
Name: species6, Length: 13471, dtype: object

In [49]:
cl_seqs["species"].iloc[-1]

'g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES'

In [33]:
cl_seqs[cl_seqs["species"].str.contains(r"\d")]

,id,seq,species
0,g003334.m1_alloascoidea_hylecoeti.final,MEQQPTQDNISNETHGSEEPPTKKSRSDNGTECETTDATPTINRNE...,g003334.m1_alloascoidea_hylecoeti
1,g002909.m1_arxula_adeninivorans.final,MAEPDQISEGHESPGSSNKRQLHEVDHSDRSPRPEDTNGTKRPRTD...,g002909.m1_arxula_adeninivorans
2,g001599.m1_ashbya_aceri.final,MALGIPYLHEYDEDTLKQRLEAVLPGLPYATQLTLKSLPLLNDIST...,g001599.m1_ashbya_aceri
3,g002398.m1_brettanomyces_anomalus.final,MADPDTSHKSPLLSENNLPHNNKKISDNVPTEEDGKKEAQTETPQI...,g002398.m1_brettanomyces_anomalus
4,C2_04200W_A_candida_albicans.cgd,MSDQLEKDIEESIANLDYQQNQEHHETEQDKDKEHQDVEKQSSEEE...,C2_04200W_A_candida_albicans
...,...,...,...
110807,g005054.m1_saccharomyces_mikatae.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005054.m1_saccharomyces_mikatae
110808,g005100.m1_saccharomyces_paradoxus.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g005100.m1_saccharomyces_paradoxus
110809,g002076.m1_saccharomyces_uvarum.final,MMDMQVRKVRKPPACTQCRKRKIGCDRAKPICGNCVKYNKPDCFYP...,g002076.m1_saccharomyces_uvarum
110810,g004724.m1_yHMPu5000034597_candida_stellimalic...,MNSNGSFKSIKGFNKVLNLIKYMLRFSKKKQNFARNSDNNNVTDYS...,g004724.m1_yHMPu5000034597_candida_stellimalic...
110811,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MYNNHFLAISLKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKY...,g005029.m1_yHRVM31_Schwanniomyces_sp_nov_plate...

In [13]:
cl_seqs[cl_seqs["species"].str.contains(r"\d")]

ValueError: Cannot mask with non-boolean array containing NA / NaN values